from __future__ import annotations


DEFAULT_LANGUAGE = "zh_CN"

LANGUAGE_OPTIONS: list[tuple[str, str]] = [
    (DEFAULT_LANGUAGE, "简体中文"),
    ("en_US", "English"),
    ("ja_JP", "日本語"),
]

LANGUAGE_LABELS = {value: label for value, label in LANGUAGE_OPTIONS}

_CURRENT_LANGUAGE = DEFAULT_LANGUAGE


def normalize_language(value: object) -> str:
    raw = str(value or DEFAULT_LANGUAGE).strip()
    return raw if raw in LANGUAGE_LABELS else DEFAULT_LANGUAGE


def set_current_language(lang: object) -> None:
    global _CURRENT_LANGUAGE
    _CURRENT_LANGUAGE = normalize_language(lang)


def get_current_language() -> str:
    return _CURRENT_LANGUAGE


def language_label(value: object) -> str:
    return LANGUAGE_LABELS[normalize_language(value)]


TEXT: dict[str, dict[str, str]] = {
    DEFAULT_LANGUAGE: {
        "menu.view": "查看",
        "menu.settings": "设置",
        "menu.help": "帮助",
        "menu.help_website": "帮助与官网",
        "dialog.help_title": "帮助与官网",
        "dialog.help_body": "需要帮助请联系，请查看官网。",
        "action.open_website": "打开官网",
        "action.close": "关闭",
        "action.cancel": "取消",
        "action.topmost_on": "已置顶",
        "action.topmost_off": "置顶",
        "action.choose_folder": "选择文件夹",
        "action.choose_image": "选择图片",
        "action.analyze_all": "分析全部",
        "action.analyze_selected": "分析选中",
        "action.repair_current": "修复选中",
        "action.repair_selected": "修复选中",
        "action.repair_checked": "批量修复勾选",
        "action.stats": "统计",
        "action.history": "更新历史",
        "action.cleanup_checked": "清理勾选项",
        "action.website": "官网",
        "action.cancel_task": "取消任务",
        "action.select_current": "选中当前",
        "action.unselect_current": "取消当前",
        "action.select_problem_items": "全选问题图",
        "action.unselect_all": "取消全部勾选",
        "action.refresh_list": "刷新列表",
        "action.cleanup_delete": "删除选择的图片",
        "action.cleanup_select_current": "勾选当前",
        "action.cleanup_toggle_selected": "切换所选",
        "action.select_all": "全选",
        "action.unselect_all_short": "取消全选",
        "action.clear_all": "取消全选",
        "common.yes": "是",
        "common.no": "否",
        "view.cleanup": "打开不适合保留的图片",
        "view.similar": "打开相似图片组",
        "view.scan_summary": "最近扫描摘要",
        "view.repair_summary": "最近修复摘要",
        "settings.app": "应用设置",
        "settings.tab.scan": "扫描",
        "settings.tab.behavior": "行为偏好",
        "settings.tab.performance": "性能",
        "settings.tab.console": "Console",
        "settings.tab.appearance": "外观 / 风格",
        "settings.tab.language": "语言",
        "settings.tab.update": "更新",
        "settings.tab.announcements": "公告",
        "settings.save": "保存设置",
        "settings.cancel": "取消",
        "settings.saved_keep_open": "应用设置已保存，设置窗口可继续修改。",
        "app.subtitle": "逐张实时分析、缩略图预览、条图诊断、自动修复与批量清理。",
        "status.ready": "请选择图片文件夹开始分析。",
        "progress.title": "任务进度",
        "filter.label": "筛选：",
        "filter.all": "全部",
        "filter.problem": "仅问题图",
        "filter.only_problem": "默认勾选问题图",
        "filter.debug_compare": "调试模式：修复后选择打开前后对比",
        "toolbar.drag_hint": "支持文件夹/图片拖入，分栏边界可拖动调整。",
        "list.title": "文件列表",
        "list.empty_stats": "未导入图片",
        "list.stats": "共 {total} 张 | 已分析 {analyzed} | 问题 {issues} | 失败 {failed} | 待清理 {cleanup} | 相似组 {similar}",
        "list.menu.toggle_pick": "切换处理状态",
        "list.menu.select_all": "全选列表",
        "list.menu.invert": "反选列表",
        "list.menu.clear": "清除列表选择",
        "list.menu.remove": "移出选中项",
        "list.action_hint": "单击处理状态可切换，右键可移出列表。",
        "tree.preview_name": "预览 / 文件名",
        "tree.pick": "处理状态",
        "tree.status": "状态",
        "tree.risk": "风险值",
        "tree.tags": "识别结果",
        "tree.selected": "已选",
        "tree.pending": "待定",
        "tree.failed": "失败",
        "tree.analyzed": "已分析",
        "tree.not_analyzed": "未分析",
        "tree.analysis_failed": "分析失败",
        "tree.normal": "正常",
        "tree.similar_group": "相似组",
        "tree.similar_marker": "相似组#{ids}",
        "cleanup.title": "不适合保留的图片",
        "cleanup.description": "分析完成后会在这里汇总可能不适合继续保留的图片。请核对后再选择是否删除。",
        "cleanup.tree_name": "缩略图 / 文件名",
        "cleanup.state": "状态",
        "cleanup.severity": "严重度",
        "cleanup.confidence": "置信度",
        "cleanup.reason": "主要原因",
        "cleanup.no_selection": "当前没有选择图片。",
        "cleanup.selected_count": "已选择 {count} 张图片。",
        "right.title": "图片信息",
        "right.diagnosis": "诊断",
        "right.preview": "预览图",
        "right.properties": "属性 / EXIF",
        "right.console": "Console",
        "summary.empty": "右下区域会显示当前图片的诊断说明、建议和推荐修复方法。",
        "summary.multi_count": "当前多选 {count} 张图片。",
        "summary.multi_analyzed": "已分析 {analyzed} 张，其中问题图 {issues} 张，待清理 {cleanup} 张。",
        "task.waiting": "等待任务",
        "task.not_started": "尚未开始。",
        "hud.no_selection": "未选择图片",
        "hud.risk_empty": "风险值 --",
        "hud.risk": "风险值 {score}",
        "hud.tags_waiting": "识别结果：等待分析",
        "hud.methods_waiting": "推荐修复：等待分析",
        "hud.multi_selected": "已多选 {count} 张图片",
        "hud.analyzed_ratio": "已分析 {done}/{total}",
        "hud.multi_tags": "识别结果：问题图 {issues} 张 | 待清理 {cleanup} 张 | 场景 {scenes}",
        "hud.multi_methods": "推荐修复：多选状态下请使用“分析选中”或“批量修复勾选”",
        "hud.analysis_failed": "识别结果：分析失败 - {error}",
        "hud.methods_read_failed": "推荐修复：请先确认图片能正常读取",
        "hud.not_analyzed": "识别结果：尚未分析",
        "hud.tags": "识别结果：{tags}",
        "hud.methods": "推荐修复：{methods}",
        "hud.methods_review": "推荐修复：{methods} | 待核对：{item}",
        "hud.methods_portrait_disabled": "推荐修复：未启用人像策略，{reason}",
        "hud.methods_keep_original": "推荐修复：可保留原图，无需额外修正",
        "hud.cleanup_hint": "可能不适合保留",
        "hud.denoise": "降噪",
        "meta.edit": "编辑",
        "meta.empty": "这里会显示 EXIF、DPI、ICC、XMP 等属性信息。",
        "meta.multi_summary": "多选状态下不显示单张 EXIF 摘要。请切回单选查看详细属性。",
        "meta.editable_broad": "可编辑字段：除软件保留项外的 EXIF / XMP / IPTC 元数据；ShapeYourPhoto 溯源字段仍会锁定。",
        "meta.readonly_reason": "编辑状态：只读。{reason}",
        "preview.empty": "选择图片后，这里会显示更大的预览图。",
        "preview.loading": "正在加载预览图...",
        "preview.load_failed": "无法加载预览图。",
    },
    "en_US": {
        "menu.view": "View",
        "menu.settings": "Settings",
        "menu.help": "Help",
        "menu.help_website": "Help & Website",
        "dialog.help_title": "Help & Website",
        "dialog.help_body": "Need help? Please contact us or visit the official website.",
        "action.open_website": "Open Website",
        "action.close": "Close",
        "action.cancel": "Cancel",
        "action.topmost_on": "Pinned",
        "action.topmost_off": "Pin",
        "action.choose_folder": "Choose Folder",
        "action.choose_image": "Choose Image",
        "action.analyze_all": "Analyze All",
        "action.analyze_selected": "Analyze Selected",
        "action.repair_current": "Repair Selected",
        "action.repair_selected": "Repair Selected",
        "action.repair_checked": "Repair Checked",
        "action.stats": "Stats",
        "action.history": "History",
        "action.cleanup_checked": "Clean Checked",
        "action.website": "Website",
        "action.cancel_task": "Cancel Task",
        "action.select_current": "Check Current",
        "action.unselect_current": "Uncheck Current",
        "action.select_problem_items": "Check Problem Images",
        "action.unselect_all": "Uncheck All",
        "action.refresh_list": "Refresh List",
        "action.cleanup_delete": "Delete Selected Images",
        "action.cleanup_select_current": "Check Current",
        "action.cleanup_toggle_selected": "Toggle Selected",
        "action.select_all": "Select All",
        "action.unselect_all_short": "Clear All",
        "action.clear_all": "Clear All",
        "common.yes": "Yes",
        "common.no": "No",
        "view.cleanup": "Unsuitable Images",
        "view.similar": "Similar Images",
        "view.scan_summary": "Recent Scan Summary",
        "view.repair_summary": "Recent Repair Summary",
        "settings.app": "App Settings",
        "settings.tab.scan": "Scan",
        "settings.tab.behavior": "Behavior",
        "settings.tab.performance": "Performance",
        "settings.tab.console": "Console",
        "settings.tab.appearance": "Appearance",
        "settings.tab.language": "Language",
        "settings.tab.update": "Updates",
        "settings.tab.announcements": "Announcements",
        "settings.save": "Save Settings",
        "settings.cancel": "Cancel",
        "settings.saved_keep_open": "Settings saved. You can keep adjusting this window.",
        "app.subtitle": "Live per-image analysis, thumbnails, diagnostic charts, automatic repair, and batch cleanup.",
        "status.ready": "Choose an image folder to start analysis.",
        "progress.title": "Task Progress",
        "filter.label": "Filter:",
        "filter.all": "All",
        "filter.problem": "Problem Images",
        "filter.only_problem": "Check problem images by default",
        "filter.debug_compare": "Debug: choose whether to open before/after comparison after repair",
        "toolbar.drag_hint": "Drop folders or images here. Drag the divider to resize panes.",
        "list.title": "Files",
        "list.empty_stats": "No images imported",
        "list.stats": "Total {total} | Analyzed {analyzed} | Issues {issues} | Failed {failed} | To review {cleanup} | Similar groups {similar}",
        "list.menu.toggle_pick": "Toggle Processing State",
        "list.menu.select_all": "Select All Rows",
        "list.menu.invert": "Invert Selection",
        "list.menu.clear": "Clear Selection",
        "list.menu.remove": "Remove Selected Rows",
        "list.action_hint": "Click processing state to toggle; right-click to remove rows.",
        "tree.preview_name": "Preview / File Name",
        "tree.pick": "Processing",
        "tree.status": "Status",
        "tree.risk": "Risk",
        "tree.tags": "Detected Issues",
        "tree.selected": "Selected",
        "tree.pending": "Pending",
        "tree.failed": "Failed",
        "tree.analyzed": "Analyzed",
        "tree.not_analyzed": "Not analyzed",
        "tree.analysis_failed": "Analysis failed",
        "tree.normal": "Normal",
        "tree.similar_group": "Similar group",
        "tree.similar_marker": "Similar group #{ids}",
        "cleanup.title": "Images Not Worth Keeping",
        "cleanup.description": "After analysis, images that may not be worth keeping appear here. Review them before deleting anything.",
        "cleanup.tree_name": "Thumbnail / File Name",
        "cleanup.state": "State",
        "cleanup.severity": "Severity",
        "cleanup.confidence": "Confidence",
        "cleanup.reason": "Main Reason",
        "cleanup.no_selection": "No image selected.",
        "cleanup.selected_count": "{count} images selected.",
        "right.title": "Image Info",
        "right.diagnosis": "Diagnosis",
        "right.preview": "Preview",
        "right.properties": "Properties / EXIF",
        "right.console": "Console",
        "summary.empty": "The lower-right area shows diagnosis notes, suggestions, and recommended repair methods for the current image.",
        "summary.multi_count": "{count} images selected.",
        "summary.multi_analyzed": "{analyzed} analyzed, {issues} issue images, {cleanup} to review.",
        "task.waiting": "Waiting",
        "task.not_started": "Not started.",
        "hud.no_selection": "No image selected",
        "hud.risk_empty": "Risk --",
        "hud.risk": "Risk {score}",
        "hud.tags_waiting": "Detected issues: waiting for analysis",
        "hud.methods_waiting": "Recommended repair: waiting for analysis",
        "hud.multi_selected": "{count} images selected",
        "hud.analyzed_ratio": "Analyzed {done}/{total}",
        "hud.multi_tags": "Detected issues: {issues} issue images | {cleanup} to review | Scenes {scenes}",
        "hud.multi_methods": "Recommended repair: use Analyze Selected or Repair Checked for multiple images",
        "hud.analysis_failed": "Detected issues: analysis failed - {error}",
        "hud.methods_read_failed": "Recommended repair: confirm this image can be opened first",
        "hud.not_analyzed": "Detected issues: not analyzed yet",
        "hud.tags": "Detected issues: {tags}",
        "hud.methods": "Recommended repair: {methods}",
        "hud.methods_review": "Recommended repair: {methods} | Review: {item}",
        "hud.methods_portrait_disabled": "Recommended repair: portrait strategy not enabled, {reason}",
        "hud.methods_keep_original": "Recommended repair: keep the original; no extra correction needed",
        "hud.cleanup_hint": "may not be worth keeping",
        "hud.denoise": "Denoise",
        "meta.edit": "Edit",
        "meta.empty": "EXIF, DPI, ICC, XMP, and other properties will appear here.",
        "meta.multi_summary": "EXIF summary is hidden while multiple images are selected. Select one image to view details.",
        "meta.editable_broad": "Editable fields: EXIF / XMP / IPTC metadata except software-reserved items. ShapeYourPhoto provenance fields remain locked.",
        "meta.readonly_reason": "Edit status: read-only. {reason}",
        "preview.empty": "Select an image to see a larger preview here.",
        "preview.loading": "Loading preview...",
        "preview.load_failed": "Unable to load preview.",
    },
    "ja_JP": {
        "menu.view": "表示",
        "menu.settings": "設定",
        "menu.help": "ヘルプ",
        "menu.help_website": "ヘルプと公式サイト",
        "dialog.help_title": "ヘルプと公式サイト",
        "dialog.help_body": "サポートが必要な場合は、公式サイトをご確認ください。",
        "action.open_website": "公式サイトを開く",
        "action.close": "閉じる",
        "action.cancel": "キャンセル",
        "action.topmost_on": "固定中",
        "action.topmost_off": "固定",
        "action.choose_folder": "フォルダーを選択",
        "action.choose_image": "画像を選択",
        "action.analyze_all": "すべて分析",
        "action.analyze_selected": "選択を分析",
        "action.repair_current": "選択を修復",
        "action.repair_selected": "選択を修復",
        "action.repair_checked": "チェック済みを一括修復",
        "action.stats": "統計",
        "action.history": "更新履歴",
        "action.cleanup_checked": "チェック項目を整理",
        "action.website": "公式サイト",
        "action.cancel_task": "タスクを中止",
        "action.select_current": "現在をチェック",
        "action.unselect_current": "現在を解除",
        "action.select_problem_items": "問題画像をチェック",
        "action.unselect_all": "すべて解除",
        "action.refresh_list": "一覧を更新",
        "action.cleanup_delete": "選択画像を削除",
        "action.cleanup_select_current": "現在をチェック",
        "action.cleanup_toggle_selected": "選択を切替",
        "action.select_all": "すべて選択",
        "action.unselect_all_short": "すべて解除",
        "action.clear_all": "すべて解除",
        "common.yes": "はい",
        "common.no": "いいえ",
        "view.cleanup": "保留に向かない画像",
        "view.similar": "類似画像グループ",
        "view.scan_summary": "最近のスキャン概要",
        "view.repair_summary": "最近の修復概要",
        "settings.app": "アプリ設定",
        "settings.tab.scan": "スキャン",
        "settings.tab.behavior": "動作設定",
        "settings.tab.performance": "性能",
        "settings.tab.console": "Console",
        "settings.tab.appearance": "外観",
        "settings.tab.language": "言語",
        "settings.tab.update": "更新",
        "settings.tab.announcements": "お知らせ",
        "settings.save": "設定を保存",
        "settings.cancel": "キャンセル",
        "settings.saved_keep_open": "設定を保存しました。このまま続けて調整できます。",
        "app.subtitle": "画像ごとのリアルタイム分析、サムネイル、診断グラフ、自動修復、まとめて整理。",
        "status.ready": "画像フォルダーを選択して分析を開始してください。",
        "progress.title": "タスク進行状況",
        "filter.label": "フィルター:",
        "filter.all": "すべて",
        "filter.problem": "問題のある画像",
        "filter.only_problem": "問題画像を既定でチェック",
        "filter.debug_compare": "デバッグ: 修復後に比較を開くか選択",
        "toolbar.drag_hint": "フォルダーや画像をドラッグできます。区切り線で幅を調整できます。",
        "list.title": "ファイル一覧",
        "list.empty_stats": "画像はまだありません",
        "list.stats": "合計 {total} | 分析済み {analyzed} | 問題 {issues} | 失敗 {failed} | 確認 {cleanup} | 類似グループ {similar}",
        "list.menu.toggle_pick": "処理状態を切替",
        "list.menu.select_all": "一覧をすべて選択",
        "list.menu.invert": "選択を反転",
        "list.menu.clear": "選択を解除",
        "list.menu.remove": "選択項目を一覧から外す",
        "list.action_hint": "処理状態をクリックで切替、右クリックで一覧から外せます。",
        "tree.preview_name": "プレビュー / ファイル名",
        "tree.pick": "処理状態",
        "tree.status": "状態",
        "tree.risk": "リスク",
        "tree.tags": "検出結果",
        "tree.selected": "選択済み",
        "tree.pending": "未選択",
        "tree.failed": "失敗",
        "tree.analyzed": "分析済み",
        "tree.not_analyzed": "未分析",
        "tree.analysis_failed": "分析失敗",
        "tree.normal": "正常",
        "tree.similar_group": "類似グループ",
        "tree.similar_marker": "類似グループ#{ids}",
        "cleanup.title": "保留に向かない画像",
        "cleanup.description": "分析後、保留に向かない可能性がある画像をここにまとめます。削除前に確認してください。",
        "cleanup.tree_name": "サムネイル / ファイル名",
        "cleanup.state": "状態",
        "cleanup.severity": "深刻度",
        "cleanup.confidence": "信頼度",
        "cleanup.reason": "主な理由",
        "cleanup.no_selection": "画像が選択されていません。",
        "cleanup.selected_count": "{count} 枚を選択中。",
        "right.title": "画像情報",
        "right.diagnosis": "診断",
        "right.preview": "プレビュー",
        "right.properties": "属性 / EXIF",
        "right.console": "Console",
        "summary.empty": "右下には、現在の画像の診断説明、提案、推奨修復方法が表示されます。",
        "summary.multi_count": "{count} 枚の画像を選択中。",
        "summary.multi_analyzed": "{analyzed} 枚分析済み、問題画像 {issues} 枚、確認 {cleanup} 枚。",
        "task.waiting": "待機中",
        "task.not_started": "まだ開始していません。",
        "hud.no_selection": "画像未選択",
        "hud.risk_empty": "リスク --",
        "hud.risk": "リスク {score}",
        "hud.tags_waiting": "検出結果：分析待ち",
        "hud.methods_waiting": "推奨修復：分析待ち",
        "hud.multi_selected": "{count} 枚を選択中",
        "hud.analyzed_ratio": "分析済み {done}/{total}",
        "hud.multi_tags": "検出結果：問題画像 {issues} 枚 | 確認 {cleanup} 枚 | シーン {scenes}",
        "hud.multi_methods": "推奨修復：複数選択では「選択を分析」または「チェック済みを一括修復」を使ってください",
        "hud.analysis_failed": "検出結果：分析失敗 - {error}",
        "hud.methods_read_failed": "推奨修復：まず画像を正常に開けるか確認してください",
        "hud.not_analyzed": "検出結果：未分析",
        "hud.tags": "検出結果：{tags}",
        "hud.methods": "推奨修復：{methods}",
        "hud.methods_review": "推奨修復：{methods} | 確認：{item}",
        "hud.methods_portrait_disabled": "推奨修復：人像方針未使用、{reason}",
        "hud.methods_keep_original": "推奨修復：元画像をそのまま保持できます",
        "hud.cleanup_hint": "保留に向かない可能性",
        "hud.denoise": "ノイズ低減",
        "meta.edit": "編集",
        "meta.empty": "EXIF、DPI、ICC、XMP などの属性情報がここに表示されます。",
        "meta.multi_summary": "複数選択中は単一画像の EXIF 概要を表示しません。1 枚だけ選択すると詳細を確認できます。",
        "meta.editable_broad": "編集可能項目：ソフトウェア保留項目を除く EXIF / XMP / IPTC メタデータ。ShapeYourPhoto 由来項目はロックされます。",
        "meta.readonly_reason": "編集状態：読み取り専用。{reason}",
        "preview.empty": "画像を選択すると、ここに大きなプレビューが表示されます。",
        "preview.loading": "プレビューを読み込み中...",
        "preview.load_failed": "プレビューを読み込めません。",
    },
}


_EXTRA_TEXT: dict[str, dict[str, str]] = {
    DEFAULT_LANGUAGE: {
        "menu.language_quick": "Language",
        "menu.contact_author": "联系作者",
        "help.faq": "常见问题",
        "help.contact": "联系作者",
        "contact.title": "联系作者",
        "contact.intro": "可以把下面的邮件模板发给作者，也可以补充自己的问题或反馈。",
        "contact.email": "联系邮箱",
        "contact.template": "邮件模板",
        "contact.extra": "补充说明",
        "contact.extra_placeholder": "请在这里补充遇到的问题、期望结果、已尝试操作或联系方式。",
        "contact.send": "发送邮件",
        "contact.copy_template": "复制模板",
        "contact.copy_email": "复制邮箱",
        "contact.open_failed": "未能打开邮件客户端。请复制模板或邮箱后手动发送。",
        "contact.copied": "已复制到剪贴板。",
        "contact.template_body": "你好，\n\n我在使用 ShapeYourPhoto 时想反馈以下问题：\n\n1. 遇到的问题：\n2. 期望的结果：\n3. 操作步骤：\n4. 系统与版本：\n\n谢谢。",
        "settings.section.scan_rules": "扫描忽略规则",
        "settings.desc.scan_rules": "这些规则只作用于文件夹名称。命中的文件夹和里面的图片会被跳过；_repair 会始终保留，避免修复输出被重新扫入。",
        "settings.rule.prefix": "前缀",
        "settings.rule.suffix": "后缀",
        "settings.rule.contains": "包含",
        "settings.rule.prefix_desc": "文件夹名称以规则开头时跳过，例如 _repair、_old。",
        "settings.rule.suffix_desc": "文件夹名称以规则结尾时跳过，例如 _backup、_old。",
        "settings.rule.contains_desc": "文件夹名称中包含规则文字时跳过。请谨慎添加，避免误跳过正常相册。",
        "settings.rule.add": "添加",
        "settings.rule.multi_hint": "列表支持按 Ctrl 或 Shift 多选后一次删除。",
        "settings.rule.remove": "删除选中",
        "settings.rule.restore": "恢复默认",
        "settings.section.default_scan": "默认扫描行为",
        "settings.desc.default_scan": "当文件夹包含子文件夹时，可以选择每次询问，或使用固定扫描模式。",
        "settings.default_scan_mode": "默认扫描模式：",
        "settings.repair_summary_filter": "修复完成详情默认筛选：",
        "settings.desc.future_tasks": "这些选项只影响之后的新任务，不会改动已经完成的分析结果。",
        "settings.section.concurrency": "分析并发",
        "settings.desc.concurrency": "控制同时分析图片的数量。通常保持自动即可；如果电脑变卡，可以调低。",
        "settings.concurrency_mode": "并发模式：",
        "settings.concurrent_workers": "同时处理数量：",
        "settings.default_workers": "当前模式默认 {count} 个",
        "settings.worker_range": "允许范围：1 到 {max} 个",
        "settings.worker_locked": "当前模式已锁定；选择“自定义同时处理数量”后可调整。",
        "settings.section.gpu": "GPU 加速",
        "settings.desc.gpu": "有可用加速能力时可以尝试开启；不可用时会自动使用 CPU。",
        "settings.gpu_mode": "GPU 加速：",
        "settings.gpu_hardware": "硬件状态：",
        "settings.gpu_backend": "加速状态：",
        "settings.gpu_detecting": "正在检测...",
        "settings.gpu_reason_detecting": "正在后台检测 GPU 硬件和可用后端，设置窗口可以继续使用。",
        "settings.gpu_available": "已找到可用加速后端；当前任务会按稳定策略选择可用路径。",
        "settings.gpu_hw_no_backend": "已检测到显卡，但当前运行环境没有可用加速后端。可以复制诊断信息，或打开帮助页面查看下一步。",
        "settings.gpu_cpu": "当前任务会继续使用 CPU。",
        "settings.gpu_check": "重新检测",
        "settings.gpu_prepare": "准备 GPU 加速",
        "settings.gpu_prepare_opened": "已打开 GPU 准备说明。",
        "settings.gpu_copy": "复制诊断信息",
        "settings.gpu_help": "查看 GPU 帮助",
        "progress.description": "请稍候，任务完成后会返回主界面。",
        "similar.skip_all": "不处理相似图",
        "similar.filter.all": "全部相似组",
        "similar.filter.high": "高相似",
        "similar.filter.medium": "中等相似",
        "similar.filter.low": "低置信候选",
        "similar.filter.large": "组内数量较多",
        "similar.filter.burst": "可能连拍/同组拍摄",
        "similar.select_visible": "全选当前筛选",
        "similar.clear_all": "取消全选",
        "similar.empty_filter": "当前筛选下没有相似组。",
        "similar.level.high": "高相似",
        "similar.level.medium": "中等相似",
        "similar.level.low": "低置信候选",
        "similar.group_title": "组 {id} | {count} 张 | {level}",
        "similar.more_count": "另 {count} 张",
        "similar.contains_cleanup": "含 {count} 张不适合保留图片",
        "similar.reason_line": "相似度 {score} | {reason}{marker}",
        "similar.cleanup_marker": "不适合保留",
        "similar.hint": "当前显示 {visible} 组，已勾选 {selected} 组。",
        "similar.decision_title": "相似图片组内对比",
        "similar.prev": "上一页",
        "similar.next": "下一页",
        "similar.skip_group": "跳过本组",
        "similar.skip_remaining": "跳过所有剩余组",
        "similar.finish": "结束选择",
        "similar.finish_all": "结束所有选择",
        "similar.delete_this": "删除此图",
        "similar.decision_group_title": "组 {id} | {index}/{total} | {count} 张",
        "analysis.running_title": "分析中 {done}/{total}",
        "analysis.start_detail": "正在分析 {total} 张图片，请稍候...",
        "analysis.dialog_title": "分析图片中",
        "analysis.dialog_header": "正在逐张分析图片",
        "analysis.cancel": "取消分析",
        "analysis.image_done_detail": "已完成第 {done}/{total} 张：{name} | 生成建议与诊断信息 | {elapsed}",
        "analysis.image_done_status": "分析进度 {done}/{total}，最近完成：{name}",
        "analysis.processing_one": "处理第 {index}/{total} 张：{name} | {phase} | {elapsed}",
        "analysis.processing_batch": "批量分析 {done}/{total} | 第 {index}/{total} 张：{name} | {phase} | {elapsed}",
        "analysis.similar_title": "检测相似图片",
        "analysis.similar_detail": "分析已完成，正在检测本轮相似图片组。{elapsed}",
        "analysis.similar_status": "正在检测相似图片组",
        "analysis.finished_title": "分析完成 {done}/{total}",
        "analysis.finished_detail": "分析完成：问题图片 {issues} 张，失败 {failed} 张，相似组 {similar} 组。",
        "analysis.phase.read": "读取图片",
        "analysis.phase.exposure": "分析曝光与画面结构",
        "analysis.phase.color": "分析色彩与清晰度",
        "analysis.phase.issue": "生成问题与修复建议",
        "analysis.phase.final": "整理诊断结果",
        "settings.section.console": "Console 时间显示",
        "settings.desc.console": "选择 Console 新日志的时间显示方式。",
        "settings.console_time": "时间格式：",
        "settings.desc.console_tz": "跨时区沟通或排查问题时，可以选择带时区的时间格式。",
        "settings.section.appearance": "应用风格",
        "settings.desc.appearance": "选择你喜欢的界面配色。",
        "settings.theme": "预置风格：",
        "settings.density": "界面清晰度 / 密度：",
        "settings.desc.density": "高清细节会略微提高字体、行高和按钮留白，适合 2K/4K 或高缩放屏幕。",
        "settings.section.language": "界面语言",
        "settings.language": "语言：",
        "settings.section.version": "当前版本",
        "settings.version_id": "版本ID {id}",
        "settings.check_updates": "检查更新",
        "settings.desc.update": "可以随时手动检查是否有新版本。",
        "settings.section.announcements": "公告",
        "settings.refresh_announcements": "刷新公告",
        "settings.no_announcements": "暂无公告。",
        "settings.refreshing_announcements": "正在刷新公告...",
        "settings.fetching_announcements": "正在获取公告。",
        "settings.announcement_retry": "稍后可以再试一次。",
        "settings.announcement_failed": "暂时没有获取到公告。",
        "settings.announcement_count": "已获取 {count} 条公告。",
        "settings.need_prefix": "至少需要保留一个目录忽略前缀。",
        "settings.save_failed": "保存失败。",
        "settings.save_failed_title": "保存失败",
        "settings.save_failed_body": "应用设置保存失败：\n{error}",
        "settings.check_unavailable": "当前无法从设置窗口发起检查。",
        "settings.copied": "已复制到剪贴板。",
        "option.scan.ask": "每次询问",
        "option.scan.all": "扫描全部，包含子文件夹",
        "option.scan.current_only": "只扫描当前文件夹",
        "option.scan.subdirs_only": "只扫描子文件夹",
        "option.summary.all": "全部",
        "option.summary.repaired": "已修复",
        "option.summary.skipped": "已跳过",
        "option.summary.failed": "失败",
        "option.summary.forced_unsaved": "强制尝试但未保存",
        "option.summary.forced_saved": "强制尝试后保存",
        "option.summary.discard_related": "不适合保留相关",
        "option.summary.rollback_noop": "回退或未保存",
        "option.worker.auto": "自动",
        "option.worker.low": "低",
        "option.worker.medium": "中",
        "option.worker.high": "高",
        "option.worker.extreme": "极高",
        "option.worker.custom": "自定义同时处理数量",
        "option.gpu.off": "关闭",
        "option.gpu.auto": "自动",
        "option.gpu.on": "开启",
        "option.console.24h": "24 小时制 [20:28:14]",
        "option.console.12h": "12 小时制 [08:28:14 PM]",
        "option.console.24h_tz": "24 小时制 + 时区 [20:28:14 UTC+09:00]",
        "option.console.elapsed": "启动后经过时间 [T+00:20:28]",
        "option.density.standard": "标准",
        "option.density.comfortable": "舒展",
        "option.density.high_detail": "高清细节",
        "scan_dialog.title": "选择文件夹扫描范围",
        "scan_dialog.heading": "当前文件夹包含子文件夹，请选择扫描范围。",
        "scan_dialog.folder": "文件夹：{folder}",
        "scan_dialog.prefix": "忽略前缀：{values}",
        "scan_dialog.suffix": "忽略后缀：{values}",
        "scan_dialog.contains": "名称包含：{values}",
        "scan_dialog.none": "无",
        "scan_dialog.rule_note": "名称符合这些规则的文件夹会被跳过，里面的图片也不会扫描。",
        "scan_dialog.all": "扫描全部，包含子文件夹",
        "scan_dialog.all_desc": "扫描当前文件夹和所有允许进入的子文件夹。",
        "scan_dialog.current": "只扫描当前文件夹",
        "scan_dialog.current_desc": "只读取当前文件夹里的图片。",
        "scan_dialog.subdirs": "只扫描子文件夹",
        "scan_dialog.subdirs_desc": "只读取子文件夹中的图片。",
        "scan_dialog.cancel": "取消扫描",
        "stats.title": "统计",
        "stats.subtitle": "显示累计分析、修复、跳过、回退、不适合保留和相似组等统计。",
        "stats.export": "导出报表",
        "stats.export_title": "导出统计报表",
        "stats.export_done": "统计报表已导出到：\n{path}",
        "stats.close": "关闭",
        "stats.issue_rate_chart": "问题检出率变化曲线",
        "stats.volume_chart": "处理数量与数据量",
        "stats.outcome_chart": "修复结果分布",
        "stats.daily_chart": "最近统计来源",
        "stats.daily_analyzed": "分析",
        "stats.daily_repaired": "修复",
        "stats.daily_scanned": "扫描",
        "stats.not_enough": "累计样本不足，图表会在分析更多图片后显示。",
        "stats.card.analysis": "累计分析",
        "stats.card.repair": "累计修复",
        "stats.card.skip_rollback": "跳过 / 回退",
        "stats.card.scan": "扫描来源",
        "stats.card.unsuitable": "不适合保留",
        "stats.card.similar": "相似组",
        "stats.card.failed_cancel": "失败 / 取消",
        "stats.card.issue_rate": "检出率",
        "stats.common_issues": "常见问题类型",
        "stats.images": "图片",
        "stats.candidate_images": "候选图片",
        "stats.groups": "累计分组",
        "stats.needs_attention": "需要关注",
        "stats.issue_images": "问题图 {count}",
        "stats.unsaved": "未保存 {count}",
        "stats.scan_rounds": "{count} 轮",
        "stats.skipped_folders": "跳过文件夹 {count}",
        "stats.analyzed": "分析图片",
        "stats.repaired": "修复图片",
        "stats.skipped": "跳过",
        "stats.scanned_files": "扫描文件",
        "diagnostics.empty": "完成分析后，这里会显示不同指标的彩色条图和风险概览。",
        "diagnostics.issue_strength": "问题强度",
        "diagnostics.no_issues": "当前未检测到明显问题。",
        "diagnostics.key_metrics": "关键指标",
        "cleanup.title": "不适合保留的图片",
        "cleanup.intro": "以下图片可能不适合继续保留。请核对后再选择是否删除。",
        "cleanup.detail_empty": "选择一张图片后，可在这里查看完整原因。",
        "cleanup.heading.file": "缩略图 / 文件名",
        "cleanup.heading.pick": "选择",
        "cleanup.heading.severity": "严重程度",
        "cleanup.heading.confidence": "置信度",
        "cleanup.heading.reason": "主要原因",
        "cleanup.pending": "待定",
        "cleanup.selected": "已选",
        "cleanup.select_current": "勾选当前",
        "cleanup.toggle_selected": "切换所选",
        "cleanup.none_selected": "当前没有选择图片，可以直接取消。",
        "cleanup.delete_selected": "删除选择的图片",
        "cleanup.detail_status": "状态",
        "cleanup.selected_hint": "已选择 {count} 张图片。",
        "history.title": "更新历史",
        "history.term.noop": "未生成新的修复版本",
        "history.term.cleanup_candidates": "不适合保留图片",
        "history.term.cleanup_similar": "不适合保留图片/相似图",
        "history.term.cleanup": "清理",
        "history.term.critical": "极其严重",
        "history.term.severe_overexposed": "严重过度曝光",
        "repair_completion.more_info": "更多批次信息在下方详情中查看。",
        "repair_completion.filter_label": "筛选：",
        "repair_completion.copy_filter": "复制当前筛选结果",
        "repair_completion.stats_fixed": "顶部统计固定显示全量结果，不会随筛选变化。",
        "repair_completion.heading.file": "文件名",
        "repair_completion.heading.status": "状态",
        "repair_completion.heading.reason": "主要原因",
        "repair_completion.heading.ops": "操作 / 跳过原因",
        "repair_completion.heading.forced": "强制",
        "repair_completion.detail_title": "选中项详情",
        "repair_completion.detail_empty": "请选择上方任一记录，查看更完整的原因、策略说明和警告。",
        "repair_completion.no_records": "当前筛选“{filter}”下没有记录。",
        "repair_completion.select_record": "请选择上方任一记录查看详情。",
        "repair_completion.record_missing": "未找到所选记录。",
        "repair_completion.forced_attempt": "强制尝试",
        "repair_completion.no_extra_detail": "没有额外详情。",
        "repair_completion.current_filter": "当前筛选",
        "repair_completion.no_copy_records": "没有可复制的记录。",
        "meta.protected": "此项由软件保留",
        "meta.save": "保存修改",
        "meta.cancel": "取消",
        "meta.developer_required": "需要先开启高级编辑。",
        "meta.exiftool_required": "当前环境暂不支持写入此项。",
        "meta.field.title": "标题 / 描述",
        "meta.field.artist": "作者",
        "meta.field.copyright": "版权",
        "meta.field.keywords": "关键词 / 备注",
        "meta.field.image_unique_id": "图片唯一标识",
        "meta.field.user_comment": "用户备注",
        "meta.field.make": "相机品牌",
        "meta.field.model": "相机型号",
        "meta.field.lens_make": "镜头品牌",
        "meta.field.lens_model": "镜头型号",
        "meta.field.date_time": "文件时间",
        "meta.field.date_original": "拍摄时间",
        "meta.field.exposure_time": "曝光时间",
        "meta.field.f_number": "光圈值",
        "meta.field.iso": "ISO",
        "meta.field.focal_length": "焦距",
        "meta.field.gps": "GPS 摘要",
        "meta.field.gps_latitude": "GPS 纬度",
        "meta.field.gps_longitude": "GPS 经度",
        "meta.field.gps_altitude": "GPS 高度",
        "meta.field.xmp_title": "XMP 标题",
        "meta.field.xmp_description": "XMP 描述",
        "meta.field.xmp_creator": "XMP 作者",
        "meta.field.xmp_rights": "XMP 版权",
        "meta.field.iptc_keywords": "IPTC 关键词",
        "meta.field.iptc_caption": "IPTC 说明",
        "meta.field.iptc_credit": "IPTC 来源 / 署名",
    },
    "en_US": {
        "menu.language_quick": "Language",
        "menu.contact_author": "Contact Author",
        "help.faq": "FAQ",
        "help.contact": "Contact Author",
        "contact.title": "Contact Author",
        "contact.intro": "You can send the email template below, and add your own question or feedback.",
        "contact.email": "Email",
        "contact.template": "Email Template",
        "contact.extra": "Extra Notes",
        "contact.extra_placeholder": "Add what happened, what you expected, steps you tried, or how to contact you.",
        "contact.send": "Send Email",
        "contact.copy_template": "Copy Template",
        "contact.copy_email": "Copy Email",
        "contact.open_failed": "Could not open your mail app. Copy the template or email address and send it manually.",
        "contact.copied": "Copied to clipboard.",
        "contact.template_body": "Hello,\n\nI would like to report the following issue while using ShapeYourPhoto:\n\n1. What happened:\n2. Expected result:\n3. Steps I tried:\n4. System and version:\n\nThank you.",
        "settings.section.scan_rules": "Scan Ignore Rules",
        "settings.desc.scan_rules": "These rules apply to folder names only. Matching folders and images inside them are skipped; _repair is always kept out of scans.",
        "settings.rule.prefix": "Prefix",
        "settings.rule.suffix": "Suffix",
        "settings.rule.contains": "Contains",
        "settings.rule.prefix_desc": "Skip folders whose names start with a rule, such as _repair or _old.",
        "settings.rule.suffix_desc": "Skip folders whose names end with a rule, such as _backup or _old.",
        "settings.rule.contains_desc": "Skip folders whose names contain the rule text. Use carefully to avoid skipping normal albums.",
        "settings.rule.add": "Add",
        "settings.rule.multi_hint": "Use Ctrl or Shift to select multiple items, then delete them together.",
        "settings.rule.remove": "Remove Selected",
        "settings.rule.restore": "Restore Default",
        "settings.section.default_scan": "Default Scan Behavior",
        "settings.desc.default_scan": "When a folder contains subfolders, choose whether to ask each time or use a fixed scan mode.",
        "settings.default_scan_mode": "Default scan mode:",
        "settings.repair_summary_filter": "Default repair summary filter:",
        "settings.desc.future_tasks": "These options affect future tasks only. Existing analysis results are not changed.",
        "settings.section.concurrency": "Analysis Concurrency",
        "settings.desc.concurrency": "Controls how many images are analyzed at the same time. Auto is usually best; lower it if the computer feels busy.",
        "settings.concurrency_mode": "Concurrency mode:",
        "settings.concurrent_workers": "Simultaneous workers:",
        "settings.default_workers": "Current mode default: {count}",
        "settings.worker_range": "Allowed range: 1 to {max}",
        "settings.worker_locked": "Locked by the current mode. Choose Custom worker count to edit it.",
        "settings.section.gpu": "GPU Acceleration",
        "settings.desc.gpu": "Use acceleration when available; otherwise ShapeYourPhoto safely uses CPU.",
        "settings.gpu_mode": "GPU acceleration:",
        "settings.gpu_hardware": "Hardware:",
        "settings.gpu_backend": "Acceleration:",
        "settings.gpu_detecting": "Checking...",
        "settings.gpu_reason_detecting": "Checking GPU hardware and available acceleration in the background.",
        "settings.gpu_available": "An acceleration backend is available; tasks will choose the stable available path.",
        "settings.gpu_hw_no_backend": "A GPU was detected, but this runtime has no usable acceleration backend. Copy diagnostics or open help for next steps.",
        "settings.gpu_cpu": "Tasks will continue on CPU.",
        "settings.gpu_check": "Check Again",
        "settings.gpu_prepare": "Prepare GPU Acceleration",
        "settings.gpu_prepare_opened": "GPU preparation help opened.",
        "settings.gpu_copy": "Copy Diagnostics",
        "settings.gpu_help": "GPU Help",
        "progress.description": "Please wait. The app will return to the main window when this task finishes.",
        "similar.skip_all": "Do Not Process Similar Images",
        "similar.filter.all": "All similar groups",
        "similar.filter.high": "High similarity",
        "similar.filter.medium": "Medium similarity",
        "similar.filter.low": "Low-confidence candidates",
        "similar.filter.large": "Larger groups",
        "similar.filter.burst": "Possible burst / same shoot",
        "similar.select_visible": "Select Current Filter",
        "similar.clear_all": "Clear All",
        "similar.empty_filter": "No similar groups match this filter.",
        "similar.level.high": "High similarity",
        "similar.level.medium": "Medium similarity",
        "similar.level.low": "Low-confidence candidate",
        "similar.group_title": "Group {id} | {count} images | {level}",
        "similar.more_count": "{count} more",
        "similar.contains_cleanup": "{count} unsuitable-image candidates",
        "similar.reason_line": "Similarity {score} | {reason}{marker}",
        "similar.cleanup_marker": "unsuitable",
        "similar.hint": "Showing {visible} groups, {selected} selected.",
        "similar.decision_title": "Compare Similar Images",
        "similar.prev": "Previous",
        "similar.next": "Next",
        "similar.skip_group": "Skip This Group",
        "similar.skip_remaining": "Skip Remaining Groups",
        "similar.finish": "Finish Selection",
        "similar.finish_all": "Finish All",
        "similar.delete_this": "Delete This Image",
        "similar.decision_group_title": "Group {id} | {index}/{total} | {count} images",
        "analysis.running_title": "Analyzing {done}/{total}",
        "analysis.start_detail": "Analyzing {total} images. Please wait...",
        "analysis.dialog_title": "Analyzing Images",
        "analysis.dialog_header": "Analyzing images one by one",
        "analysis.cancel": "Cancel Analysis",
        "analysis.image_done_detail": "Finished {done}/{total}: {name} | Preparing suggestions and diagnostics | {elapsed}",
        "analysis.image_done_status": "Analysis {done}/{total}, latest: {name}",
        "analysis.processing_one": "Processing {index}/{total}: {name} | {phase} | {elapsed}",
        "analysis.processing_batch": "Batch analysis {done}/{total} | Image {index}/{total}: {name} | {phase} | {elapsed}",
        "analysis.similar_title": "Detecting Similar Images",
        "analysis.similar_detail": "Analysis is complete. Detecting similar-image groups for this run. {elapsed}",
        "analysis.similar_status": "Detecting similar-image groups",
        "analysis.finished_title": "Analysis Complete {done}/{total}",
        "analysis.finished_detail": "Analysis complete: {issues} issue images, {failed} failed, {similar} similar groups.",
        "analysis.phase.read": "Reading image",
        "analysis.phase.exposure": "Analyzing exposure and structure",
        "analysis.phase.color": "Analyzing color and sharpness",
        "analysis.phase.issue": "Preparing issues and repair suggestions",
        "analysis.phase.final": "Preparing diagnostics",
        "settings.section.console": "Console Time Display",
        "settings.desc.console": "Choose how new Console log timestamps are shown.",
        "settings.console_time": "Time format:",
        "settings.desc.console_tz": "Use a timezone format when sharing logs across time zones.",
        "settings.section.appearance": "Appearance",
        "settings.desc.appearance": "Choose the color style you prefer.",
        "settings.theme": "Theme:",
        "settings.density": "UI density:",
        "settings.desc.density": "High detail slightly increases font size, row height, and button padding for 2K/4K or scaled displays.",
        "settings.section.language": "Interface Language",
        "settings.language": "Language:",
        "settings.section.version": "Current Version",
        "settings.version_id": "Version ID {id}",
        "settings.check_updates": "Check Updates",
        "settings.desc.update": "You can manually check for a new version at any time.",
        "settings.section.announcements": "Announcements",
        "settings.refresh_announcements": "Refresh Announcements",
        "settings.no_announcements": "No announcements.",
        "settings.refreshing_announcements": "Refreshing announcements...",
        "settings.fetching_announcements": "Fetching announcements.",
        "settings.announcement_retry": "Please try again later.",
        "settings.announcement_failed": "No announcement was available.",
        "settings.announcement_count": "Fetched {count} announcement(s).",
        "settings.need_prefix": "Keep at least one folder ignore prefix.",
        "settings.save_failed": "Save failed.",
        "settings.save_failed_title": "Save Failed",
        "settings.save_failed_body": "Could not save app settings:\n{error}",
        "settings.check_unavailable": "Update checks are not available from this window right now.",
        "settings.copied": "Copied to clipboard.",
        "option.scan.ask": "Ask each time",
        "option.scan.all": "Scan all, including subfolders",
        "option.scan.current_only": "Scan current folder only",
        "option.scan.subdirs_only": "Scan subfolders only",
        "option.summary.all": "All",
        "option.summary.repaired": "Repaired",
        "option.summary.skipped": "Skipped",
        "option.summary.failed": "Failed",
        "option.summary.forced_unsaved": "Forced attempt not saved",
        "option.summary.forced_saved": "Saved after forced attempt",
        "option.summary.discard_related": "Unsuitable-image related",
        "option.summary.rollback_noop": "Rolled back or not saved",
        "option.worker.auto": "Auto",
        "option.worker.low": "Low",
        "option.worker.medium": "Medium",
        "option.worker.high": "High",
        "option.worker.extreme": "Extreme",
        "option.worker.custom": "Custom worker count",
        "option.gpu.off": "Off",
        "option.gpu.auto": "Auto",
        "option.gpu.on": "On",
        "option.console.24h": "24-hour time [20:28:14]",
        "option.console.12h": "12-hour time [08:28:14 PM]",
        "option.console.24h_tz": "24-hour time + timezone [20:28:14 UTC+09:00]",
        "option.console.elapsed": "Elapsed since launch [T+00:20:28]",
        "option.density.standard": "Standard",
        "option.density.comfortable": "Comfortable",
        "option.density.high_detail": "High detail",
        "scan_dialog.title": "Choose Folder Scan Range",
        "scan_dialog.heading": "This folder contains subfolders. Choose the scan range.",
        "scan_dialog.folder": "Folder: {folder}",
        "scan_dialog.prefix": "Ignored prefixes: {values}",
        "scan_dialog.suffix": "Ignored suffixes: {values}",
        "scan_dialog.contains": "Name contains: {values}",
        "scan_dialog.none": "None",
        "scan_dialog.rule_note": "Folders matching these rules will be skipped, including images inside them.",
        "scan_dialog.all": "Scan All, Including Subfolders",
        "scan_dialog.all_desc": "Scan the current folder and all allowed subfolders.",
        "scan_dialog.current": "Scan Current Folder Only",
        "scan_dialog.current_desc": "Read only images directly inside the current folder.",
        "scan_dialog.subdirs": "Scan Subfolders Only",
        "scan_dialog.subdirs_desc": "Read only images inside subfolders.",
        "scan_dialog.cancel": "Cancel Scan",
        "stats.title": "Stats",
        "stats.subtitle": "Shows cumulative analysis, repair, skipped, rollback, unsuitable-image, and similar-group statistics.",
        "stats.export": "Export Report",
        "stats.export_title": "Export Stats Report",
        "stats.export_done": "Stats report exported to:\n{path}",
        "stats.close": "Close",
        "stats.issue_rate_chart": "Issue Rate Trend",
        "stats.volume_chart": "Processed Count and Data Size",
        "stats.outcome_chart": "Repair Outcome Distribution",
        "stats.daily_chart": "Recent Stat Sources",
        "stats.daily_analyzed": "Analyzed",
        "stats.daily_repaired": "Repaired",
        "stats.daily_scanned": "Scanned",
        "stats.not_enough": "More samples are needed before this chart appears.",
        "stats.card.analysis": "Analyzed",
        "stats.card.repair": "Repaired",
        "stats.card.skip_rollback": "Skipped / Rolled Back",
        "stats.card.scan": "Scan Sources",
        "stats.card.unsuitable": "Unsuitable",
        "stats.card.similar": "Similar Groups",
        "stats.card.failed_cancel": "Failed / Canceled",
        "stats.card.issue_rate": "Issue Rate",
        "stats.common_issues": "Common Issue Types",
        "stats.images": "images",
        "stats.candidate_images": "candidate images",
        "stats.groups": "groups total",
        "stats.needs_attention": "needs attention",
        "stats.issue_images": "{count} issue images",
        "stats.unsaved": "{count} not saved",
        "stats.scan_rounds": "{count} runs",
        "stats.skipped_folders": "{count} folders skipped",
        "stats.analyzed": "Analyzed images",
        "stats.repaired": "Repaired images",
        "stats.skipped": "Skipped",
        "stats.scanned_files": "Scanned files",
        "diagnostics.empty": "After analysis, colored metric bars and a risk overview will appear here.",
        "diagnostics.issue_strength": "Issue Strength",
        "diagnostics.no_issues": "No obvious issues detected.",
        "diagnostics.key_metrics": "Key Metrics",
        "cleanup.title": "Unsuitable Images",
        "cleanup.intro": "These images may not be worth keeping. Review them before deleting anything.",
        "cleanup.detail_empty": "Select an image to view the full reason here.",
        "cleanup.heading.file": "Thumbnail / File",
        "cleanup.heading.pick": "Pick",
        "cleanup.heading.severity": "Severity",
        "cleanup.heading.confidence": "Confidence",
        "cleanup.heading.reason": "Main Reason",
        "cleanup.pending": "Pending",
        "cleanup.selected": "Selected",
        "cleanup.select_current": "Check Current",
        "cleanup.toggle_selected": "Toggle Selected",
        "cleanup.none_selected": "No images are selected. You can cancel directly.",
        "cleanup.delete_selected": "Delete Selected Images",
        "cleanup.detail_status": "Status",
        "cleanup.selected_hint": "{count} images selected.",
        "history.title": "Update History",
        "history.term.noop": "No new repaired version",
        "history.term.cleanup_candidates": "unsuitable images",
        "history.term.cleanup_similar": "unsuitable/similar images",
        "history.term.cleanup": "cleanup",
        "history.term.critical": "severe",
        "history.term.severe_overexposed": "severely overexposed",
        "repair_completion.more_info": "More batch details are available below.",
        "repair_completion.filter_label": "Filter:",
        "repair_completion.copy_filter": "Copy Current Filter",
        "repair_completion.stats_fixed": "Top stats always show the full batch and do not change with the filter.",
        "repair_completion.heading.file": "File Name",
        "repair_completion.heading.status": "Status",
        "repair_completion.heading.reason": "Main Reason",
        "repair_completion.heading.ops": "Action / Skip Reason",
        "repair_completion.heading.forced": "Forced",
        "repair_completion.detail_title": "Selected Item Details",
        "repair_completion.detail_empty": "Select any record above to view full reasons, policy notes, and warnings.",
        "repair_completion.no_records": "No records under the current filter \"{filter}\".",
        "repair_completion.select_record": "Select a record above to view details.",
        "repair_completion.record_missing": "Selected record was not found.",
        "repair_completion.forced_attempt": "Forced attempt",
        "repair_completion.no_extra_detail": "No extra details.",
        "repair_completion.current_filter": "Current filter",
        "repair_completion.no_copy_records": "No records to copy.",
        "meta.protected": "Reserved by ShapeYourPhoto",
        "meta.save": "Save Changes",
        "meta.cancel": "Cancel",
        "meta.developer_required": "Enable advanced editing first.",
        "meta.exiftool_required": "This item cannot be written in the current environment.",
        "meta.field.title": "Title / Description",
        "meta.field.artist": "Author",
        "meta.field.copyright": "Copyright",
        "meta.field.keywords": "Keywords / Notes",
        "meta.field.image_unique_id": "Image Unique ID",
        "meta.field.user_comment": "User Comment",
        "meta.field.make": "Camera Make",
        "meta.field.model": "Camera Model",
        "meta.field.lens_make": "Lens Make",
        "meta.field.lens_model": "Lens Model",
        "meta.field.date_time": "File Time",
        "meta.field.date_original": "Date Taken",
        "meta.field.exposure_time": "Exposure Time",
        "meta.field.f_number": "Aperture",
        "meta.field.iso": "ISO",
        "meta.field.focal_length": "Focal Length",
        "meta.field.gps": "GPS Summary",
        "meta.field.gps_latitude": "GPS Latitude",
        "meta.field.gps_longitude": "GPS Longitude",
        "meta.field.gps_altitude": "GPS Altitude",
        "meta.field.xmp_title": "XMP Title",
        "meta.field.xmp_description": "XMP Description",
        "meta.field.xmp_creator": "XMP Creator",
        "meta.field.xmp_rights": "XMP Rights",
        "meta.field.iptc_keywords": "IPTC Keywords",
        "meta.field.iptc_caption": "IPTC Caption",
        "meta.field.iptc_credit": "IPTC Credit",
    },
    "ja_JP": {
        "menu.language_quick": "Language",
        "menu.contact_author": "作者に連絡",
        "help.faq": "よくある質問",
        "help.contact": "作者に連絡",
        "contact.title": "作者に連絡",
        "contact.intro": "下のメールテンプレートを送信し、必要に応じて質問やフィードバックを追加できます。",
        "contact.email": "メール",
        "contact.template": "メールテンプレート",
        "contact.extra": "補足",
        "contact.extra_placeholder": "発生した問題、期待した結果、試した操作、連絡先などを入力してください。",
        "contact.send": "メールを送る",
        "contact.copy_template": "テンプレートをコピー",
        "contact.copy_email": "メールをコピー",
        "contact.open_failed": "メールアプリを開けませんでした。テンプレートまたはメールアドレスをコピーして手動で送信してください。",
        "contact.copied": "クリップボードにコピーしました。",
        "contact.template_body": "こんにちは。\n\nShapeYourPhoto の使用中に、以下の件を報告したいです。\n\n1. 発生した問題：\n2. 期待した結果：\n3. 試した操作：\n4. システムとバージョン：\n\nよろしくお願いします。",
        "settings.section.scan_rules": "スキャン除外ルール",
        "settings.desc.scan_rules": "これらのルールはフォルダー名だけに適用されます。一致したフォルダーと中の画像はスキップされます。_repair は常に除外されます。",
        "settings.rule.prefix": "接頭辞",
        "settings.rule.suffix": "接尾辞",
        "settings.rule.contains": "含む",
        "settings.rule.prefix_desc": "_repair や _old など、名前がこの文字で始まるフォルダーをスキップします。",
        "settings.rule.suffix_desc": "_backup や _old など、名前がこの文字で終わるフォルダーをスキップします。",
        "settings.rule.contains_desc": "名前にこの文字を含むフォルダーをスキップします。通常のアルバムを誤って除外しないよう注意してください。",
        "settings.rule.add": "追加",
        "settings.rule.multi_hint": "Ctrl または Shift で複数選択し、一括削除できます。",
        "settings.rule.remove": "選択を削除",
        "settings.rule.restore": "既定に戻す",
        "settings.section.default_scan": "既定のスキャン動作",
        "settings.desc.default_scan": "サブフォルダーがある場合、毎回確認するか固定のスキャン方式を使えます。",
        "settings.default_scan_mode": "既定のスキャン方式：",
        "settings.repair_summary_filter": "修復完了詳細の既定フィルター：",
        "settings.desc.future_tasks": "これらの設定は今後のタスクだけに反映され、完了済みの分析結果は変更しません。",
        "settings.section.concurrency": "分析の同時処理",
        "settings.desc.concurrency": "同時に分析する画像数を制御します。通常は自動がおすすめです。重い場合は下げてください。",
        "settings.concurrency_mode": "同時処理モード：",
        "settings.concurrent_workers": "同時処理数：",
        "settings.default_workers": "現在の既定値：{count}",
        "settings.worker_range": "設定範囲：1 から {max}",
        "settings.worker_locked": "現在のモードで固定されています。指定モードを選ぶと変更できます。",
        "settings.section.gpu": "GPU アクセラレーション",
        "settings.desc.gpu": "利用できる場合はアクセラレーションを試します。利用できない場合は安全に CPU を使います。",
        "settings.gpu_mode": "GPU：",
        "settings.gpu_hardware": "ハードウェア：",
        "settings.gpu_backend": "アクセラレーション：",
        "settings.gpu_detecting": "確認中...",
        "settings.gpu_reason_detecting": "GPU ハードウェアと利用可能なアクセラレーションをバックグラウンドで確認しています。",
        "settings.gpu_available": "利用可能なアクセラレーションが見つかりました。タスクは安定した利用可能経路を選択します。",
        "settings.gpu_hw_no_backend": "GPU は検出されましたが、現在の実行環境に利用可能なアクセラレーションがありません。診断情報をコピーするか、ヘルプを確認してください。",
        "settings.gpu_cpu": "タスクは CPU で続行します。",
        "settings.gpu_check": "再確認",
        "settings.gpu_prepare": "GPU 加速を準備",
        "settings.gpu_prepare_opened": "GPU 準備の説明を開きました。",
        "settings.gpu_copy": "診断をコピー",
        "settings.gpu_help": "GPU ヘルプ",
        "progress.description": "しばらくお待ちください。完了後、メイン画面に戻ります。",
        "similar.skip_all": "類似画像を処理しない",
        "similar.filter.all": "すべての類似グループ",
        "similar.filter.high": "高い類似",
        "similar.filter.medium": "中程度の類似",
        "similar.filter.low": "低信頼候補",
        "similar.filter.large": "枚数が多いグループ",
        "similar.filter.burst": "連写 / 同じ撮影の可能性",
        "similar.select_visible": "現在の絞り込みを選択",
        "similar.clear_all": "すべて解除",
        "similar.empty_filter": "この絞り込みに一致する類似グループはありません。",
        "similar.level.high": "高い類似",
        "similar.level.medium": "中程度の類似",
        "similar.level.low": "低信頼候補",
        "similar.group_title": "グループ {id} | {count} 枚 | {level}",
        "similar.more_count": "ほか {count} 枚",
        "similar.contains_cleanup": "保留に向かない候補 {count} 枚を含む",
        "similar.reason_line": "類似度 {score} | {reason}{marker}",
        "similar.cleanup_marker": "保留に向かない",
        "similar.hint": "{visible} グループを表示中、{selected} グループ選択済み。",
        "similar.decision_title": "類似画像の比較",
        "similar.prev": "前へ",
        "similar.next": "次へ",
        "similar.skip_group": "このグループをスキップ",
        "similar.skip_remaining": "残りをすべてスキップ",
        "similar.finish": "選択を終了",
        "similar.finish_all": "すべて終了",
        "similar.delete_this": "この画像を削除",
        "similar.decision_group_title": "グループ {id} | {index}/{total} | {count} 枚",
        "analysis.running_title": "分析中 {done}/{total}",
        "analysis.start_detail": "{total} 枚の画像を分析しています。しばらくお待ちください...",
        "analysis.dialog_title": "画像を分析中",
        "analysis.dialog_header": "画像を 1 枚ずつ分析しています",
        "analysis.cancel": "分析を中止",
        "analysis.image_done_detail": "{done}/{total} 枚目が完了：{name} | 提案と診断を生成 | {elapsed}",
        "analysis.image_done_status": "分析進行 {done}/{total}、最近完了：{name}",
        "analysis.processing_one": "{index}/{total} 枚目を処理：{name} | {phase} | {elapsed}",
        "analysis.processing_batch": "一括分析 {done}/{total} | {index}/{total} 枚目：{name} | {phase} | {elapsed}",
        "analysis.similar_title": "類似画像を検出",
        "analysis.similar_detail": "分析が完了しました。この回の類似画像グループを検出しています。{elapsed}",
        "analysis.similar_status": "類似画像グループを検出中",
        "analysis.finished_title": "分析完了 {done}/{total}",
        "analysis.finished_detail": "分析完了：問題画像 {issues} 枚、失敗 {failed} 枚、類似グループ {similar} 件。",
        "analysis.phase.read": "画像を読み込み",
        "analysis.phase.exposure": "露出と構図を分析",
        "analysis.phase.color": "色と鮮明さを分析",
        "analysis.phase.issue": "問題と修復提案を生成",
        "analysis.phase.final": "診断結果を整理",
        "settings.section.console": "Console 時刻表示",
        "settings.desc.console": "Console の新しいログ時刻の表示方式を選びます。",
        "settings.console_time": "時刻形式：",
        "settings.desc.console_tz": "タイムゾーンをまたぐ共有では、タイムゾーン付き形式が便利です。",
        "settings.section.appearance": "外観",
        "settings.desc.appearance": "好みの配色を選びます。",
        "settings.theme": "テーマ：",
        "settings.density": "表示密度：",
        "settings.desc.density": "高精細ではフォント、行高、ボタン余白が少し増えます。2K/4K や拡大表示に向いています。",
        "settings.section.language": "表示言語",
        "settings.language": "言語：",
        "settings.section.version": "現在のバージョン",
        "settings.version_id": "バージョンID {id}",
        "settings.check_updates": "更新を確認",
        "settings.desc.update": "いつでも新しいバージョンを手動で確認できます。",
        "settings.section.announcements": "お知らせ",
        "settings.refresh_announcements": "お知らせを更新",
        "settings.no_announcements": "お知らせはありません。",
        "settings.refreshing_announcements": "お知らせを更新中...",
        "settings.fetching_announcements": "お知らせを取得中です。",
        "settings.announcement_retry": "後でもう一度お試しください。",
        "settings.announcement_failed": "お知らせを取得できませんでした。",
        "settings.announcement_count": "{count} 件のお知らせを取得しました。",
        "settings.need_prefix": "フォルダー除外接頭辞を少なくとも 1 つ残してください。",
        "settings.save_failed": "保存できませんでした。",
        "settings.save_failed_title": "保存失敗",
        "settings.save_failed_body": "アプリ設定を保存できませんでした：\n{error}",
        "settings.check_unavailable": "このウィンドウからは現在、更新確認を開始できません。",
        "settings.copied": "クリップボードにコピーしました。",
        "option.scan.ask": "毎回確認",
        "option.scan.all": "すべてスキャン（サブフォルダーを含む）",
        "option.scan.current_only": "現在のフォルダーのみ",
        "option.scan.subdirs_only": "サブフォルダーのみ",
        "option.summary.all": "すべて",
        "option.summary.repaired": "修復済み",
        "option.summary.skipped": "スキップ済み",
        "option.summary.failed": "失敗",
        "option.summary.forced_unsaved": "強制試行・未保存",
        "option.summary.forced_saved": "強制試行後に保存",
        "option.summary.discard_related": "保留に向かない画像関連",
        "option.summary.rollback_noop": "回退または未保存",
        "option.worker.auto": "自動",
        "option.worker.low": "低",
        "option.worker.medium": "中",
        "option.worker.high": "高",
        "option.worker.extreme": "極高",
        "option.worker.custom": "同時処理数を指定",
        "option.gpu.off": "オフ",
        "option.gpu.auto": "自動",
        "option.gpu.on": "オン",
        "option.console.24h": "24 時間制 [20:28:14]",
        "option.console.12h": "12 時間制 [08:28:14 PM]",
        "option.console.24h_tz": "24 時間制 + タイムゾーン [20:28:14 UTC+09:00]",
        "option.console.elapsed": "起動後の経過時間 [T+00:20:28]",
        "option.density.standard": "標準",
        "option.density.comfortable": "ゆったり",
        "option.density.high_detail": "高精細",
        "scan_dialog.title": "フォルダーのスキャン範囲を選択",
        "scan_dialog.heading": "現在のフォルダーにはサブフォルダーがあります。スキャン範囲を選択してください。",
        "scan_dialog.folder": "フォルダー：{folder}",
        "scan_dialog.prefix": "除外接頭辞：{values}",
        "scan_dialog.suffix": "除外接尾辞：{values}",
        "scan_dialog.contains": "名前に含む：{values}",
        "scan_dialog.none": "なし",
        "scan_dialog.rule_note": "これらのルールに一致するフォルダーと中の画像はスキャンされません。",
        "scan_dialog.all": "すべてスキャン（サブフォルダーを含む）",
        "scan_dialog.all_desc": "現在のフォルダーと許可されたすべてのサブフォルダーをスキャンします。",
        "scan_dialog.current": "現在のフォルダーのみ",
        "scan_dialog.current_desc": "現在のフォルダー直下の画像だけを読み込みます。",
        "scan_dialog.subdirs": "サブフォルダーのみ",
        "scan_dialog.subdirs_desc": "サブフォルダー内の画像だけを読み込みます。",
        "scan_dialog.cancel": "スキャンを中止",
        "stats.title": "統計",
        "stats.subtitle": "累計分析、修復、スキップ、回退、保留に向かない画像、類似グループなどの統計を表示します。",
        "stats.export": "レポートを書き出す",
        "stats.export_title": "統計レポートを書き出す",
        "stats.export_done": "統計レポートを書き出しました：\n{path}",
        "stats.close": "閉じる",
        "stats.issue_rate_chart": "問題検出率の推移",
        "stats.volume_chart": "処理数とデータ量",
        "stats.outcome_chart": "修復結果の分布",
        "stats.daily_chart": "最近の統計ソース",
        "stats.daily_analyzed": "分析",
        "stats.daily_repaired": "修復",
        "stats.daily_scanned": "スキャン",
        "stats.not_enough": "サンプルが増えると、このグラフが表示されます。",
        "stats.card.analysis": "累計分析",
        "stats.card.repair": "累計修復",
        "stats.card.skip_rollback": "スキップ / 回退",
        "stats.card.scan": "スキャン元",
        "stats.card.unsuitable": "保留に向かない画像",
        "stats.card.similar": "類似グループ",
        "stats.card.failed_cancel": "失敗 / 中止",
        "stats.card.issue_rate": "検出率",
        "stats.common_issues": "よくある問題タイプ",
        "stats.images": "画像",
        "stats.candidate_images": "候補画像",
        "stats.groups": "累計グループ",
        "stats.needs_attention": "確認が必要",
        "stats.issue_images": "問題画像 {count}",
        "stats.unsaved": "未保存 {count}",
        "stats.scan_rounds": "{count} 回",
        "stats.skipped_folders": "スキップフォルダー {count}",
        "stats.analyzed": "分析画像",
        "stats.repaired": "修復画像",
        "stats.skipped": "スキップ",
        "stats.scanned_files": "スキャンファイル",
        "diagnostics.empty": "分析後、指標別のカラーバーとリスク概要がここに表示されます。",
        "diagnostics.issue_strength": "問題の強さ",
        "diagnostics.no_issues": "明らかな問題は検出されていません。",
        "diagnostics.key_metrics": "主要指標",
        "cleanup.title": "保留に向かない画像",
        "cleanup.intro": "これらの画像は保留に向かない可能性があります。削除前に確認してください。",
        "cleanup.detail_empty": "画像を選択すると、詳しい理由がここに表示されます。",
        "cleanup.heading.file": "サムネイル / ファイル名",
        "cleanup.heading.pick": "選択",
        "cleanup.heading.severity": "深刻度",
        "cleanup.heading.confidence": "信頼度",
        "cleanup.heading.reason": "主な理由",
        "cleanup.pending": "保留",
        "cleanup.selected": "選択済み",
        "cleanup.select_current": "現在を選択",
        "cleanup.toggle_selected": "選択を切替",
        "cleanup.none_selected": "画像は選択されていません。そのままキャンセルできます。",
        "cleanup.delete_selected": "選択画像を削除",
        "cleanup.detail_status": "状態",
        "cleanup.selected_hint": "{count} 枚の画像を選択しました。",
        "history.title": "更新履歴",
        "history.term.noop": "新しい修復版なし",
        "history.term.cleanup_candidates": "保留に向かない画像",
        "history.term.cleanup_similar": "保留に向かない画像/類似画像",
        "history.term.cleanup": "整理",
        "history.term.critical": "非常に深刻",
        "history.term.severe_overexposed": "重度の露出オーバー",
        "repair_completion.more_info": "追加のバッチ情報は下の詳細で確認できます。",
        "repair_completion.filter_label": "フィルター：",
        "repair_completion.copy_filter": "現在のフィルター結果をコピー",
        "repair_completion.stats_fixed": "上部の統計は全体結果を表示し、フィルターでは変わりません。",
        "repair_completion.heading.file": "ファイル名",
        "repair_completion.heading.status": "状態",
        "repair_completion.heading.reason": "主な理由",
        "repair_completion.heading.ops": "操作 / スキップ理由",
        "repair_completion.heading.forced": "強制",
        "repair_completion.detail_title": "選択項目の詳細",
        "repair_completion.detail_empty": "上の記録を選択すると、理由、方針、警告を確認できます。",
        "repair_completion.no_records": "現在のフィルター「{filter}」に記録はありません。",
        "repair_completion.select_record": "上の記録を選択して詳細を表示してください。",
        "repair_completion.record_missing": "選択した記録が見つかりません。",
        "repair_completion.forced_attempt": "強制試行",
        "repair_completion.no_extra_detail": "追加の詳細はありません。",
        "repair_completion.current_filter": "現在のフィルター",
        "repair_completion.no_copy_records": "コピーできる記録はありません。",
        "meta.protected": "ShapeYourPhoto が保持する項目です",
        "meta.save": "変更を保存",
        "meta.cancel": "キャンセル",
        "meta.developer_required": "先に高度な編集を有効にしてください。",
        "meta.exiftool_required": "現在の環境ではこの項目を書き込めません。",
        "meta.field.title": "タイトル / 説明",
        "meta.field.artist": "作者",
        "meta.field.copyright": "著作権",
        "meta.field.keywords": "キーワード / メモ",
        "meta.field.image_unique_id": "画像固有 ID",
        "meta.field.user_comment": "ユーザーコメント",
        "meta.field.make": "カメラメーカー",
        "meta.field.model": "カメラモデル",
        "meta.field.lens_make": "レンズメーカー",
        "meta.field.lens_model": "レンズモデル",
        "meta.field.date_time": "ファイル時刻",
        "meta.field.date_original": "撮影日時",
        "meta.field.exposure_time": "露出時間",
        "meta.field.f_number": "絞り値",
        "meta.field.iso": "ISO",
        "meta.field.focal_length": "焦点距離",
        "meta.field.gps": "GPS 概要",
        "meta.field.gps_latitude": "GPS 緯度",
        "meta.field.gps_longitude": "GPS 経度",
        "meta.field.gps_altitude": "GPS 高度",
        "meta.field.xmp_title": "XMP タイトル",
        "meta.field.xmp_description": "XMP 説明",
        "meta.field.xmp_creator": "XMP 作成者",
        "meta.field.xmp_rights": "XMP 権利",
        "meta.field.iptc_keywords": "IPTC キーワード",
        "meta.field.iptc_caption": "IPTC 説明",
        "meta.field.iptc_credit": "IPTC クレジット",
    },
}


for _lang, _values in _EXTRA_TEXT.items():
    TEXT.setdefault(_lang, {}).update(_values)

TEXT[DEFAULT_LANGUAGE].update({
    "settings.saved_keep_open": "设置已保存，可继续调整。",
    "tree.pick": "状态",
    "tree.status": "分析状态",
    "action.format_convert": "无损格式转换",
    "format.title": "批量无损格式转换",
    "format.no_selection": "请先勾选或选择需要转换的图片。",
    "format.hint": "将转换 {count} 张图片。",
    "format.desc": "PNG / WebP 使用无损模式；JPG 使用最高质量并保留 EXIF，但 JPG 格式本身不是绝对无损。",
    "format.target": "目标格式：",
    "format.output_dir": "输出目录：",
    "format.choose_dir": "选择目录",
    "format.start": "开始转换",
    "format.done": "转换完成：成功 {ok}，失败 {failed}。输出目录：{output}",
    "format.finish_after_current": "提前结束",
    "format.progress_counts": "第 {index}/{total} 张 | 成功 {ok} | 失败 {failed} | 跳过 {skipped} | 耗时 {elapsed}",
    "format.current_file": "当前文件：{filename}",
    "format.canceling": "正在取消并回滚本轮转换结果...",
    "format.finishing_after_current": "将完成当前图片后提前结束。",
    "format.canceled": "转换已取消，已回滚本轮已生成的 {rolled} 个输出。",
    "format.early_done": "已提前结束：成功 {ok}，失败 {failed}，跳过 {skipped}。输出目录：{output}",
    "format.rollback_progress": "回滚 {index}/{total}：{filename}",
    "gps.edit": "GPS",
    "gps.title": "GPS 信息",
    "gps.desc": "输入经纬度即可写回图片 GPS 信息。正数表示北纬/东经，负数表示南纬/西经；保存会保留其他元数据并生成备份。",
    "gps.latitude": "纬度：",
    "gps.longitude": "经度：",
    "gps.empty": "当前图片没有 GPS 信息。",
    "gps.existing": "已读取当前 GPS 信息，可直接修改。",
    "gps.map_hint": "地图选点",
    "gps.map_placeholder": "地图选点入口已预留；当前可先输入经纬度或从地图服务复制坐标。",
    "gps.save_failed": "GPS 写入失败，已尽量回退原文件：{error}",
    "gps.saved": "GPS 已保存，备份文件：{backup}",
    "settings.tab.logs": "日志",
    "settings.section.logs": "日志管理",
    "settings.desc.logs": "日志默认写入 data/logs，并包含 Console 中的重要操作记录。详细模式用于排障，简洁模式减少普通运行噪声。",
    "settings.log_level": "日志级别：",
    "settings.log_language": "日志语言：",
    "settings.log_retention": "自动清理：",
    "settings.log_retention_unit": "天（0 表示不清理）",
    "settings.desc.logs_retention": "默认清理一个月以前的日志；需要长期排障时可改为不清理。",
    "settings.desc.logs_export": "可从“帮助 -> 导出日志”导出当前和近期日志用于反馈问题。",
    "option.log_level.detailed": "详细",
    "option.log_level.brief": "简洁",
    "option.log_language.follow_ui": "跟随界面语言",
    "option.log_language.bilingual": "双语输出",
    "log.export": "导出日志",
    "log.export_done": "日志已导出：\n{path}",
    "settings.gpu_prepare_confirm": "将尝试安装 GPU 加速依赖。此过程可能需要网络和数分钟时间；失败时仍会继续使用 CPU。是否开始？",
    "settings.gpu_prepare_running": "正在准备 GPU 加速依赖，请保持窗口打开。",
    "settings.gpu_prepare_done": "GPU 依赖准备完成，正在重新检测。",
    "settings.gpu_prepare_failed": "GPU 依赖准备失败。已保持 CPU 稳定路径，可复制诊断继续排障。",
    "analysis.no_targets_title": "没有可处理图片",
    "analysis.no_targets_all": "当前列表中没有可分析的图片。请先添加图片。",
    "analysis.no_targets_selected": "请先在当前列表中选择需要分析的图片。",
    "meta.dialog_title": "编辑属性 / EXIF",
    "meta.editable_whitelist": "可编辑：标题、描述、作者、版权、关键词和备注。相机信息等只读项会保留原样，软件保留项会锁定。",
    "meta.confirm_title": "确认保存",
    "meta.confirm_body": "确认保存这些修改吗？保存前会自动创建备份。",
    "meta.filename_readonly": "文件名不是 EXIF 字段，当前仅显示。",
    "meta.readonly_camera": "只读信息",
    "meta.readonly_orientation": "方向信息由图像显示使用",
    "meta.readonly_binary": "二进制色彩配置不在此处修改",
    "meta.readonly_makernote": "厂商私有信息保持原样",
    "meta.save_failed_title": "保存失败",
    "meta.save_failed_body": "写入失败，原文件已尽量恢复：\n{error}",
    "meta.saved": "已保存修改，备份：{backup}",
    "meta.field.filename": "文件名",
})

TEXT["en_US"].update({
    "settings.saved_keep_open": "Settings saved. You can keep editing.",
    "tree.pick": "State",
    "tree.status": "Analysis",
    "action.format_convert": "Lossless Convert",
    "format.title": "Batch Lossless Format Conversion",
    "format.no_selection": "Select or check images to convert first.",
    "format.hint": "{count} images will be converted.",
    "format.desc": "PNG and WebP use lossless mode. JPG uses maximum quality and keeps EXIF, but JPG itself is not truly lossless.",
    "format.target": "Target format:",
    "format.output_dir": "Output folder:",
    "format.choose_dir": "Choose",
    "format.start": "Start",
    "format.done": "Done: {ok} succeeded, {failed} failed. Output: {output}",
    "format.finish_after_current": "Finish Current",
    "format.progress_counts": "{index}/{total} | Success {ok} | Failed {failed} | Skipped {skipped} | Elapsed {elapsed}",
    "format.current_file": "Current file: {filename}",
    "format.canceling": "Canceling and rolling back converted files...",
    "format.finishing_after_current": "The current image will finish, then the batch will stop.",
    "format.canceled": "Conversion canceled. Rolled back {rolled} output file(s).",
    "format.early_done": "Stopped early: {ok} succeeded, {failed} failed, {skipped} skipped. Output: {output}",
    "format.rollback_progress": "Rollback {index}/{total}: {filename}",
    "gps.edit": "GPS",
    "gps.title": "GPS Info",
    "gps.desc": "Enter latitude and longitude to write GPS metadata. Positive means north/east; negative means south/west. Other metadata is preserved and a backup is created.",
    "gps.latitude": "Latitude:",
    "gps.longitude": "Longitude:",
    "gps.empty": "This image has no GPS data.",
    "gps.existing": "Existing GPS data loaded.",
    "gps.map_hint": "Map Pick",
    "gps.map_placeholder": "Map picking is reserved here. For now, paste coordinates from a map service.",
    "gps.save_failed": "GPS save failed and the file was restored where possible: {error}",
    "gps.saved": "GPS saved. Backup: {backup}",
    "settings.tab.logs": "Logs",
    "settings.section.logs": "Log Management",
    "settings.desc.logs": "Logs are written to data/logs and include important Console operations. Detailed mode is best for troubleshooting; brief mode is quieter.",
    "settings.log_level": "Log level:",
    "settings.log_language": "Log language:",
    "settings.log_retention": "Auto cleanup:",
    "settings.log_retention_unit": "days (0 means never)",
    "settings.desc.logs_retention": "The default removes logs older than about one month. Set 0 for long troubleshooting sessions.",
    "settings.desc.logs_export": "Use Help -> Export Logs to package current and recent logs for feedback.",
    "option.log_level.detailed": "Detailed",
    "option.log_level.brief": "Brief",
    "option.log_language.follow_ui": "Follow UI language",
    "option.log_language.bilingual": "Bilingual",
    "log.export": "Export Logs",
    "log.export_done": "Logs exported:\n{path}",
    "settings.gpu_prepare_confirm": "ShapeYourPhoto will try to install GPU acceleration dependencies. This may need network access and several minutes. CPU fallback remains available. Start now?",
    "settings.gpu_prepare_running": "Preparing GPU acceleration dependencies. Keep this window open.",
    "settings.gpu_prepare_done": "GPU dependencies are ready. Rechecking now.",
    "settings.gpu_prepare_failed": "GPU dependency setup failed. CPU fallback remains available; copy diagnostics for troubleshooting.",
    "analysis.no_targets_title": "No Images To Process",
    "analysis.no_targets_all": "There are no images in the current list to analyze. Add images first.",
    "analysis.no_targets_selected": "Select images from the current list before analyzing.",
    "meta.dialog_title": "Edit Properties / EXIF",
    "meta.editable_whitelist": "Editable: title, description, author, copyright, keywords, and notes. Camera data stays read-only and software-reserved items stay locked.",
    "meta.confirm_title": "Confirm Save",
    "meta.confirm_body": "Save these changes? A backup will be created first.",
    "meta.filename_readonly": "File name is not an EXIF field and is shown read-only here.",
    "meta.readonly_camera": "Read-only information",
    "meta.readonly_orientation": "Orientation is used for image display",
    "meta.readonly_binary": "Binary color profile data is not edited here",
    "meta.readonly_makernote": "Vendor private data is kept unchanged",
    "meta.save_failed_title": "Save Failed",
    "meta.save_failed_body": "Save failed and the original file was restored where possible:\n{error}",
    "meta.saved": "Changes saved. Backup: {backup}",
    "meta.field.filename": "File name",
})

TEXT["ja_JP"].update({
    "settings.saved_keep_open": "設定を保存しました。続けて調整できます。",
    "tree.pick": "状態",
    "tree.status": "分析状態",
    "action.format_convert": "無損変換",
    "format.title": "一括無損形式変換",
    "format.no_selection": "変換する画像を先に選択してください。",
    "format.hint": "{count} 枚の画像を変換します。",
    "format.desc": "PNG / WebP は無損モードを使います。JPG は最高品質で EXIF を保持しますが、形式上完全な無損ではありません。",
    "format.target": "形式：",
    "format.output_dir": "出力先：",
    "format.choose_dir": "選択",
    "format.start": "開始",
    "format.done": "完了：成功 {ok}、失敗 {failed}。出力先：{output}",
    "format.finish_after_current": "現在分で終了",
    "format.progress_counts": "{index}/{total} 枚目 | 成功 {ok} | 失敗 {failed} | スキップ {skipped} | 経過 {elapsed}",
    "format.current_file": "現在のファイル：{filename}",
    "format.canceling": "キャンセルして今回の変換結果を戻しています...",
    "format.finishing_after_current": "現在の画像が完了したら終了します。",
    "format.canceled": "変換をキャンセルしました。{rolled} 個の出力を戻しました。",
    "format.early_done": "途中終了：成功 {ok}、失敗 {failed}、スキップ {skipped}。出力先：{output}",
    "format.rollback_progress": "ロールバック {index}/{total}：{filename}",
    "gps.edit": "GPS",
    "gps.title": "GPS 情報",
    "gps.desc": "緯度と経度を入力して GPS 情報を書き込みます。正数は北緯/東経、負数は南緯/西経です。他のメタデータは保持し、バックアップを作成します。",
    "gps.latitude": "緯度：",
    "gps.longitude": "経度：",
    "gps.empty": "この画像には GPS 情報がありません。",
    "gps.existing": "現在の GPS 情報を読み込みました。",
    "gps.map_hint": "地図で選択",
    "gps.map_placeholder": "地図選択はこの入口に統合予定です。今は地図サービスから座標を貼り付けてください。",
    "gps.save_failed": "GPS 保存に失敗しました。可能な範囲で元に戻しました：{error}",
    "gps.saved": "GPS を保存しました。バックアップ：{backup}",
    "settings.tab.logs": "ログ",
    "settings.section.logs": "ログ管理",
    "settings.desc.logs": "ログは data/logs に保存され、Console の重要な操作も含みます。詳細は調査向け、簡潔は通常利用向けです。",
    "settings.log_level": "ログレベル：",
    "settings.log_language": "ログ言語：",
    "settings.log_retention": "自動整理：",
    "settings.log_retention_unit": "日（0 は整理しない）",
    "settings.desc.logs_retention": "既定では約 1 か月以上前のログを整理します。長期調査では 0 にできます。",
    "settings.desc.logs_export": "「ヘルプ -> ログを書き出す」から現在と最近のログをまとめて出力できます。",
    "option.log_level.detailed": "詳細",
    "option.log_level.brief": "簡潔",
    "option.log_language.follow_ui": "画面言語に合わせる",
    "option.log_language.bilingual": "二言語出力",
    "log.export": "ログを書き出す",
    "log.export_done": "ログを書き出しました：\n{path}",
    "settings.gpu_prepare_confirm": "GPU アクセラレーション依存関係の準備を試します。ネットワークと数分の時間が必要な場合があります。失敗しても CPU で続行できます。開始しますか？",
    "settings.gpu_prepare_running": "GPU 依存関係を準備しています。このウィンドウを開いたままにしてください。",
    "settings.gpu_prepare_done": "GPU 依存関係の準備が完了しました。再確認しています。",
    "settings.gpu_prepare_failed": "GPU 依存関係の準備に失敗しました。CPU で安定して続行できます。診断をコピーして確認してください。",
    "analysis.no_targets_title": "処理できる画像がありません",
    "analysis.no_targets_all": "現在の一覧に分析できる画像がありません。先に画像を追加してください。",
    "analysis.no_targets_selected": "分析する画像を現在の一覧から選択してください。",
    "meta.dialog_title": "プロパティ / EXIF を編集",
    "meta.editable_whitelist": "編集可能：タイトル、説明、作者、著作権、キーワード、メモ。カメラ情報は読み取り専用、ソフトウェア保持項目はロックされます。",
    "meta.confirm_title": "保存の確認",
    "meta.confirm_body": "変更を保存しますか？保存前にバックアップを作成します。",
    "meta.filename_readonly": "ファイル名は EXIF 項目ではないため、ここでは表示のみです。",
    "meta.readonly_camera": "読み取り専用情報",
    "meta.readonly_orientation": "向き情報は画像表示に使われます",
    "meta.readonly_binary": "バイナリの色設定はここでは編集しません",
    "meta.readonly_makernote": "メーカー固有情報はそのまま保持します",
    "meta.save_failed_title": "保存に失敗しました",
    "meta.save_failed_body": "保存に失敗しました。可能な範囲で元のファイルに戻しました：\n{error}",
    "meta.saved": "変更を保存しました。バックアップ：{backup}",
    "meta.field.filename": "ファイル名",
})


TEXT[DEFAULT_LANGUAGE].update({
    "settings.gpu_prepare": "运行加速自检",
    "settings.gpu_component_missing": "当前安装包缺少 GPU 加速组件，已自动回退 CPU。请重新安装完整版本或使用官方 GPU 组件包。",
    "settings.gpu_native_fallback": "Native GPU 组件已找到，但本机暂时无法启用加速；程序会自动使用 CPU 回退。",
    "settings.gpu_self_test_running": "正在运行 Native GPU 加速自检。",
    "settings.gpu_self_test_done": "Native GPU 加速自检通过，支持的分析任务会自动使用 GPU。",
    "settings.gpu_self_test_fallback": "Native GPU 自检未通过，已自动回退 CPU；可复制诊断日志排查安装组件或驱动状态。",
})

TEXT["en_US"].update({
    "settings.gpu_prepare": "Run Self-Test",
    "settings.gpu_component_missing": "This package is missing the bundled GPU acceleration component. CPU fallback is active; reinstall the full build or use the official GPU component package.",
    "settings.gpu_native_fallback": "The native GPU component is present but acceleration could not start on this computer. CPU fallback is active.",
    "settings.gpu_self_test_running": "Running the native GPU acceleration self-test.",
    "settings.gpu_self_test_done": "Native GPU self-test passed. Supported analysis tasks will use GPU automatically.",
    "settings.gpu_self_test_fallback": "Native GPU self-test did not pass. CPU fallback is active; copy diagnostics to inspect component or driver status.",
})

TEXT["ja_JP"].update({
    "settings.gpu_prepare": "加速自检",
    "settings.gpu_component_missing": "GPU 加速组件未包含在当前安装包中。已自动回退 CPU，请重新安装完整版本或使用官方组件包。",
    "settings.gpu_native_fallback": "Native GPU 组件已找到，但当前设备无法启用加速；已自动回退 CPU。",
    "settings.gpu_self_test_running": "Native GPU 加速自检正在运行。",
    "settings.gpu_self_test_done": "Native GPU 自检通过，支持的分析任务会自动使用 GPU。",
    "settings.gpu_self_test_fallback": "Native GPU 自检未通过，已自动回退 CPU；可复制诊断继续排查。",
})


def tr(key: str) -> str:
    lang = normalize_language(get_current_language())
    return TEXT.get(lang, TEXT[DEFAULT_LANGUAGE]).get(key, TEXT[DEFAULT_LANGUAGE].get(key, key))
