from __future__ import annotations


DEFAULT_LANGUAGE = "zh_CN"

LANGUAGE_OPTIONS: list[tuple[str, str]] = [
    (DEFAULT_LANGUAGE, "简体中文"),
    ("en_US", "English"),
    ("ja_JP", "日本語"),
]

LANGUAGE_LABELS = {value: label for value, label in LANGUAGE_OPTIONS}

_CURRENT_LANGUAGE = DEFAULT_LANGUAGE


def normalize_language(value: object) -> str:
    raw = str(value or DEFAULT_LANGUAGE).strip()
    return raw if raw in LANGUAGE_LABELS else DEFAULT_LANGUAGE


def set_current_language(lang: object) -> None:
    global _CURRENT_LANGUAGE
    _CURRENT_LANGUAGE = normalize_language(lang)


def get_current_language() -> str:
    return _CURRENT_LANGUAGE


def language_label(value: object) -> str:
    return LANGUAGE_LABELS[normalize_language(value)]


TEXT: dict[str, dict[str, str]] = {
    DEFAULT_LANGUAGE: {
        "menu.view": "查看",
        "menu.settings": "设置",
        "menu.help": "帮助",
        "menu.help_website": "帮助与官网",
        "dialog.help_title": "帮助与官网",
        "dialog.help_body": "需要帮助请联系，请查看官网。",
        "action.open_website": "打开官网",
        "action.close": "关闭",
        "action.topmost_on": "已置顶",
        "action.topmost_off": "置顶",
        "action.choose_folder": "选择文件夹",
        "action.choose_image": "选择图片",
        "action.analyze_all": "分析全部",
        "action.analyze_selected": "分析选中",
        "action.repair_current": "修复当前",
        "action.repair_checked": "批量修复勾选",
        "action.stats": "统计",
        "action.history": "更新历史",
        "action.cleanup_checked": "清理勾选项",
        "action.website": "官网",
        "action.cancel_task": "取消任务",
        "action.select_current": "选中当前",
        "action.unselect_current": "取消当前",
        "action.select_problem_items": "全选问题图",
        "action.unselect_all": "取消全部勾选",
        "action.refresh_list": "刷新列表",
        "action.cleanup_delete": "删除选择的图片",
        "action.cleanup_select_current": "勾选当前",
        "action.cleanup_toggle_selected": "切换所选",
        "action.select_all": "全选",
        "action.unselect_all_short": "取消全选",
        "view.cleanup": "打开不适合保留的图片",
        "view.similar": "打开相似图片组",
        "view.scan_summary": "最近扫描摘要",
        "view.repair_summary": "最近修复摘要",
        "settings.app": "应用设置",
        "settings.tab.scan": "扫描",
        "settings.tab.behavior": "行为偏好",
        "settings.tab.performance": "性能",
        "settings.tab.console": "Console",
        "settings.tab.appearance": "外观 / 风格",
        "settings.tab.language": "语言",
        "settings.tab.update": "更新",
        "settings.tab.announcements": "公告",
        "settings.save": "保存设置",
        "settings.cancel": "取消",
        "settings.saved_keep_open": "应用设置已保存，设置窗口可继续修改。",
        "app.subtitle": "逐张实时分析、缩略图预览、条图诊断、自动修复与批量清理。",
        "status.ready": "请选择图片文件夹开始分析。",
        "progress.title": "任务进度",
        "filter.label": "筛选：",
        "filter.all": "全部",
        "filter.problem": "仅问题图",
        "filter.only_problem": "默认勾选问题图",
        "filter.debug_compare": "调试模式：修复后选择打开前后对比",
        "toolbar.drag_hint": "支持文件夹/图片拖入，分栏边界可拖动调整。",
        "list.title": "文件列表",
        "list.empty_stats": "未导入图片",
        "list.menu.toggle_pick": "切换处理状态",
        "list.menu.select_all": "全选列表",
        "list.menu.invert": "反选列表",
        "list.menu.clear": "清除列表选择",
        "list.menu.remove": "移出选中项",
        "list.action_hint": "单击处理状态可切换，右键可移出列表。",
        "tree.preview_name": "预览 / 文件名",
        "tree.pick": "处理状态",
        "tree.status": "状态",
        "tree.risk": "风险值",
        "tree.tags": "识别结果",
        "cleanup.title": "不适合保留的图片",
        "cleanup.description": "分析完成后会在这里汇总可能不适合继续保留的图片。请核对后再选择是否删除。",
        "cleanup.tree_name": "缩略图 / 文件名",
        "cleanup.state": "状态",
        "cleanup.severity": "严重度",
        "cleanup.confidence": "置信度",
        "cleanup.reason": "主要原因",
        "cleanup.no_selection": "当前没有选择图片。",
        "right.title": "图片信息",
        "right.diagnosis": "诊断",
        "right.preview": "预览图",
        "right.properties": "属性 / EXIF",
        "right.console": "Console",
        "summary.empty": "右下区域会显示当前图片的诊断说明、建议和推荐修复方法。",
        "meta.edit": "编辑",
        "meta.empty": "这里会显示 EXIF、DPI、ICC、XMP 等属性信息。",
        "preview.empty": "选择图片后，这里会显示更大的预览图。",
        "preview.loading": "正在加载预览图...",
        "preview.load_failed": "无法加载预览图。",
    },
    "en_US": {
        "menu.view": "View",
        "menu.settings": "Settings",
        "menu.help": "Help",
        "menu.help_website": "Help & Website",
        "dialog.help_title": "Help & Website",
        "dialog.help_body": "Need help? Please contact us or visit the official website.",
        "action.open_website": "Open Website",
        "action.close": "Close",
        "action.topmost_on": "Pinned",
        "action.topmost_off": "Pin",
        "action.choose_folder": "Choose Folder",
        "action.choose_image": "Choose Image",
        "action.analyze_all": "Analyze All",
        "action.analyze_selected": "Analyze Selected",
        "action.repair_current": "Repair Current",
        "action.repair_checked": "Repair Checked",
        "action.stats": "Stats",
        "action.history": "History",
        "action.cleanup_checked": "Clean Checked",
        "action.website": "Website",
        "action.cancel_task": "Cancel Task",
        "action.select_current": "Check Current",
        "action.unselect_current": "Uncheck Current",
        "action.select_problem_items": "Check Problem Images",
        "action.unselect_all": "Uncheck All",
        "action.refresh_list": "Refresh List",
        "action.cleanup_delete": "Delete Selected Images",
        "action.cleanup_select_current": "Check Current",
        "action.cleanup_toggle_selected": "Toggle Selected",
        "action.select_all": "Select All",
        "action.unselect_all_short": "Clear All",
        "view.cleanup": "Unsuitable Images",
        "view.similar": "Similar Images",
        "view.scan_summary": "Recent Scan Summary",
        "view.repair_summary": "Recent Repair Summary",
        "settings.app": "App Settings",
        "settings.tab.scan": "Scan",
        "settings.tab.behavior": "Behavior",
        "settings.tab.performance": "Performance",
        "settings.tab.console": "Console",
        "settings.tab.appearance": "Appearance",
        "settings.tab.language": "Language",
        "settings.tab.update": "Updates",
        "settings.tab.announcements": "Announcements",
        "settings.save": "Save Settings",
        "settings.cancel": "Cancel",
        "settings.saved_keep_open": "Settings saved. You can keep adjusting this window.",
        "app.subtitle": "Live per-image analysis, thumbnails, diagnostic charts, automatic repair, and batch cleanup.",
        "status.ready": "Choose an image folder to start analysis.",
        "progress.title": "Task Progress",
        "filter.label": "Filter:",
        "filter.all": "All",
        "filter.problem": "Problem Images",
        "filter.only_problem": "Check problem images by default",
        "filter.debug_compare": "Debug: choose whether to open before/after comparison after repair",
        "toolbar.drag_hint": "Drop folders or images here. Drag the divider to resize panes.",
        "list.title": "Files",
        "list.empty_stats": "No images imported",
        "list.menu.toggle_pick": "Toggle Processing State",
        "list.menu.select_all": "Select All Rows",
        "list.menu.invert": "Invert Selection",
        "list.menu.clear": "Clear Selection",
        "list.menu.remove": "Remove Selected Rows",
        "list.action_hint": "Click processing state to toggle; right-click to remove rows.",
        "tree.preview_name": "Preview / File Name",
        "tree.pick": "Processing",
        "tree.status": "Status",
        "tree.risk": "Risk",
        "tree.tags": "Detected Issues",
        "cleanup.title": "Images Not Worth Keeping",
        "cleanup.description": "After analysis, images that may not be worth keeping appear here. Review them before deleting anything.",
        "cleanup.tree_name": "Thumbnail / File Name",
        "cleanup.state": "State",
        "cleanup.severity": "Severity",
        "cleanup.confidence": "Confidence",
        "cleanup.reason": "Main Reason",
        "cleanup.no_selection": "No image selected.",
        "right.title": "Image Info",
        "right.diagnosis": "Diagnosis",
        "right.preview": "Preview",
        "right.properties": "Properties / EXIF",
        "right.console": "Console",
        "summary.empty": "The lower-right area shows diagnosis notes, suggestions, and recommended repair methods for the current image.",
        "meta.edit": "Edit",
        "meta.empty": "EXIF, DPI, ICC, XMP, and other properties will appear here.",
        "preview.empty": "Select an image to see a larger preview here.",
        "preview.loading": "Loading preview...",
        "preview.load_failed": "Unable to load preview.",
    },
    "ja_JP": {
        "menu.view": "表示",
        "menu.settings": "設定",
        "menu.help": "ヘルプ",
        "menu.help_website": "ヘルプと公式サイト",
        "dialog.help_title": "ヘルプと公式サイト",
        "dialog.help_body": "サポートが必要な場合は、公式サイトをご確認ください。",
        "action.open_website": "公式サイトを開く",
        "action.close": "閉じる",
        "action.topmost_on": "固定中",
        "action.topmost_off": "固定",
        "action.choose_folder": "フォルダーを選択",
        "action.choose_image": "画像を選択",
        "action.analyze_all": "すべて分析",
        "action.analyze_selected": "選択を分析",
        "action.repair_current": "現在の画像を修復",
        "action.repair_checked": "チェック済みを一括修復",
        "action.stats": "統計",
        "action.history": "更新履歴",
        "action.cleanup_checked": "チェック項目を整理",
        "action.website": "公式サイト",
        "action.cancel_task": "タスクを中止",
        "action.select_current": "現在をチェック",
        "action.unselect_current": "現在を解除",
        "action.select_problem_items": "問題画像をチェック",
        "action.unselect_all": "すべて解除",
        "action.refresh_list": "一覧を更新",
        "action.cleanup_delete": "選択画像を削除",
        "action.cleanup_select_current": "現在をチェック",
        "action.cleanup_toggle_selected": "選択を切替",
        "action.select_all": "すべて選択",
        "action.unselect_all_short": "すべて解除",
        "view.cleanup": "保留に向かない画像",
        "view.similar": "類似画像グループ",
        "view.scan_summary": "最近のスキャン概要",
        "view.repair_summary": "最近の修復概要",
        "settings.app": "アプリ設定",
        "settings.tab.scan": "スキャン",
        "settings.tab.behavior": "動作設定",
        "settings.tab.performance": "性能",
        "settings.tab.console": "Console",
        "settings.tab.appearance": "外観",
        "settings.tab.language": "言語",
        "settings.tab.update": "更新",
        "settings.tab.announcements": "お知らせ",
        "settings.save": "設定を保存",
        "settings.cancel": "キャンセル",
        "settings.saved_keep_open": "設定を保存しました。このまま続けて調整できます。",
        "app.subtitle": "画像ごとのリアルタイム分析、サムネイル、診断グラフ、自動修復、まとめて整理。",
        "status.ready": "画像フォルダーを選択して分析を開始してください。",
        "progress.title": "タスク進行状況",
        "filter.label": "フィルター:",
        "filter.all": "すべて",
        "filter.problem": "問題のある画像",
        "filter.only_problem": "問題画像を既定でチェック",
        "filter.debug_compare": "デバッグ: 修復後に比較を開くか選択",
        "toolbar.drag_hint": "フォルダーや画像をドラッグできます。区切り線で幅を調整できます。",
        "list.title": "ファイル一覧",
        "list.empty_stats": "画像はまだありません",
        "list.menu.toggle_pick": "処理状態を切替",
        "list.menu.select_all": "一覧をすべて選択",
        "list.menu.invert": "選択を反転",
        "list.menu.clear": "選択を解除",
        "list.menu.remove": "選択項目を一覧から外す",
        "list.action_hint": "処理状態をクリックで切替、右クリックで一覧から外せます。",
        "tree.preview_name": "プレビュー / ファイル名",
        "tree.pick": "処理状態",
        "tree.status": "状態",
        "tree.risk": "リスク",
        "tree.tags": "検出結果",
        "cleanup.title": "保留に向かない画像",
        "cleanup.description": "分析後、保留に向かない可能性がある画像をここにまとめます。削除前に確認してください。",
        "cleanup.tree_name": "サムネイル / ファイル名",
        "cleanup.state": "状態",
        "cleanup.severity": "深刻度",
        "cleanup.confidence": "信頼度",
        "cleanup.reason": "主な理由",
        "cleanup.no_selection": "画像が選択されていません。",
        "right.title": "画像情報",
        "right.diagnosis": "診断",
        "right.preview": "プレビュー",
        "right.properties": "属性 / EXIF",
        "right.console": "Console",
        "summary.empty": "右下には、現在の画像の診断説明、提案、推奨修復方法が表示されます。",
        "meta.edit": "編集",
        "meta.empty": "EXIF、DPI、ICC、XMP などの属性情報がここに表示されます。",
        "preview.empty": "画像を選択すると、ここに大きなプレビューが表示されます。",
        "preview.loading": "プレビューを読み込み中...",
        "preview.load_failed": "プレビューを読み込めません。",
    },
}


_EXTRA_TEXT: dict[str, dict[str, str]] = {
    DEFAULT_LANGUAGE: {
        "menu.language_quick": "Language",
        "menu.contact_author": "联系作者",
        "help.faq": "常见问题",
        "help.contact": "联系作者",
        "contact.title": "联系作者",
        "contact.intro": "可以把下面的邮件模板发给作者，也可以补充自己的问题或反馈。",
        "contact.email": "联系邮箱",
        "contact.template": "邮件模板",
        "contact.extra": "补充说明",
        "contact.extra_placeholder": "请在这里补充遇到的问题、期望结果、已尝试操作或联系方式。",
        "contact.send": "发送邮件",
        "contact.copy_template": "复制模板",
        "contact.copy_email": "复制邮箱",
        "contact.open_failed": "未能打开邮件客户端。请复制模板或邮箱后手动发送。",
        "contact.copied": "已复制到剪贴板。",
        "contact.template_body": "你好，\n\n我在使用 ShapeYourPhoto 时想反馈以下问题：\n\n1. 遇到的问题：\n2. 期望的结果：\n3. 操作步骤：\n4. 系统与版本：\n\n谢谢。",
        "settings.section.scan_rules": "扫描忽略规则",
        "settings.desc.scan_rules": "这些规则只作用于文件夹名称。命中的文件夹和里面的图片会被跳过；_repair 会始终保留，避免修复输出被重新扫入。",
        "settings.rule.prefix": "前缀",
        "settings.rule.suffix": "后缀",
        "settings.rule.contains": "包含",
        "settings.rule.prefix_desc": "文件夹名称以规则开头时跳过，例如 _repair、_old。",
        "settings.rule.suffix_desc": "文件夹名称以规则结尾时跳过，例如 _backup、_old。",
        "settings.rule.contains_desc": "文件夹名称中包含规则文字时跳过。请谨慎添加，避免误跳过正常相册。",
        "settings.rule.add": "添加",
        "settings.rule.multi_hint": "列表支持按 Ctrl 或 Shift 多选后一次删除。",
        "settings.rule.remove": "删除选中",
        "settings.rule.restore": "恢复默认",
        "settings.section.default_scan": "默认扫描行为",
        "settings.desc.default_scan": "当文件夹包含子文件夹时，可以选择每次询问，或使用固定扫描模式。",
        "settings.default_scan_mode": "默认扫描模式：",
        "settings.repair_summary_filter": "修复完成详情默认筛选：",
        "settings.desc.future_tasks": "这些选项只影响之后的新任务，不会改动已经完成的分析结果。",
        "settings.section.concurrency": "分析并发",
        "settings.desc.concurrency": "控制同时分析图片的数量。通常保持自动即可；如果电脑变卡，可以调低。",
        "settings.concurrency_mode": "并发模式：",
        "settings.concurrent_workers": "同时处理数量：",
        "settings.default_workers": "当前模式默认 {count} 个",
        "settings.worker_range": "允许范围：1 到 {max} 个",
        "settings.section.gpu": "GPU 加速",
        "settings.desc.gpu": "有可用加速能力时可以尝试开启；不可用时会自动使用 CPU。",
        "settings.gpu_mode": "GPU 加速：",
        "settings.gpu_hardware": "硬件状态：",
        "settings.gpu_backend": "加速状态：",
        "settings.gpu_detecting": "正在检测...",
        "settings.gpu_reason_detecting": "正在后台检测 GPU 硬件和可用后端，设置窗口可以继续使用。",
        "settings.gpu_available": "已找到可用加速后端；当前任务会按稳定策略选择可用路径。",
        "settings.gpu_hw_no_backend": "已检测到显卡，但当前运行环境没有可用加速后端。可以复制诊断信息，或打开帮助页面查看下一步。",
        "settings.gpu_cpu": "当前任务会继续使用 CPU。",
        "settings.gpu_check": "重新检测",
        "settings.gpu_copy": "复制诊断信息",
        "settings.gpu_help": "查看 GPU 帮助",
        "settings.section.console": "Console 时间显示",
        "settings.desc.console": "选择 Console 新日志的时间显示方式。",
        "settings.console_time": "时间格式：",
        "settings.desc.console_tz": "跨时区沟通或排查问题时，可以选择带时区的时间格式。",
        "settings.section.appearance": "应用风格",
        "settings.desc.appearance": "选择你喜欢的界面配色。",
        "settings.theme": "预置风格：",
        "settings.density": "界面清晰度 / 密度：",
        "settings.desc.density": "高清细节会略微提高字体、行高和按钮留白，适合 2K/4K 或高缩放屏幕。",
        "settings.section.language": "界面语言",
        "settings.language": "语言：",
        "settings.section.version": "当前版本",
        "settings.version_id": "版本ID {id}",
        "settings.check_updates": "检查更新",
        "settings.desc.update": "可以随时手动检查是否有新版本。",
        "settings.section.announcements": "公告",
        "settings.refresh_announcements": "刷新公告",
        "settings.no_announcements": "暂无公告。",
        "settings.refreshing_announcements": "正在刷新公告...",
        "settings.fetching_announcements": "正在获取公告。",
        "settings.announcement_retry": "稍后可以再试一次。",
        "settings.announcement_failed": "暂时没有获取到公告。",
        "settings.announcement_count": "已获取 {count} 条公告。",
        "settings.need_prefix": "至少需要保留一个目录忽略前缀。",
        "settings.save_failed": "保存失败。",
        "settings.save_failed_title": "保存失败",
        "settings.save_failed_body": "应用设置保存失败：\n{error}",
        "settings.check_unavailable": "当前无法从设置窗口发起检查。",
        "settings.copied": "已复制到剪贴板。",
        "option.scan.ask": "每次询问",
        "option.scan.all": "扫描全部，包含子文件夹",
        "option.scan.current_only": "只扫描当前文件夹",
        "option.scan.subdirs_only": "只扫描子文件夹",
        "option.summary.all": "全部",
        "option.summary.repaired": "已修复",
        "option.summary.skipped": "已跳过",
        "option.summary.failed": "失败",
        "option.summary.forced_unsaved": "强制尝试但未保存",
        "option.summary.forced_saved": "强制尝试后保存",
        "option.summary.discard_related": "不适合保留相关",
        "option.summary.rollback_noop": "回退或未保存",
        "option.worker.auto": "自动",
        "option.worker.low": "低",
        "option.worker.medium": "中",
        "option.worker.high": "高",
        "option.worker.extreme": "极高",
        "option.worker.custom": "自定义同时处理数量",
        "option.gpu.off": "关闭",
        "option.gpu.auto": "自动",
        "option.gpu.on": "开启",
        "option.console.24h": "24 小时制 [20:28:14]",
        "option.console.12h": "12 小时制 [08:28:14 PM]",
        "option.console.24h_tz": "24 小时制 + 时区 [20:28:14 UTC+09:00]",
        "option.console.elapsed": "启动后经过时间 [T+00:20:28]",
        "option.density.standard": "标准",
        "option.density.comfortable": "舒展",
        "option.density.high_detail": "高清细节",
        "scan_dialog.title": "选择文件夹扫描范围",
        "scan_dialog.heading": "当前文件夹包含子文件夹，请选择扫描范围。",
        "scan_dialog.folder": "文件夹：{folder}",
        "scan_dialog.prefix": "忽略前缀：{values}",
        "scan_dialog.suffix": "忽略后缀：{values}",
        "scan_dialog.contains": "名称包含：{values}",
        "scan_dialog.none": "无",
        "scan_dialog.rule_note": "名称符合这些规则的文件夹会被跳过，里面的图片也不会扫描。",
        "scan_dialog.all": "扫描全部，包含子文件夹",
        "scan_dialog.all_desc": "扫描当前文件夹和所有允许进入的子文件夹。",
        "scan_dialog.current": "只扫描当前文件夹",
        "scan_dialog.current_desc": "只读取当前文件夹里的图片。",
        "scan_dialog.subdirs": "只扫描子文件夹",
        "scan_dialog.subdirs_desc": "只读取子文件夹中的图片。",
        "scan_dialog.cancel": "取消扫描",
        "stats.title": "统计",
        "stats.subtitle": "显示累计分析、修复、跳过、回退、不适合保留和相似组等统计。",
        "stats.export": "导出报表",
        "stats.export_title": "导出统计报表",
        "stats.export_done": "统计报表已导出到：\n{path}",
        "stats.close": "关闭",
        "stats.issue_rate_chart": "问题检出率变化曲线",
        "stats.volume_chart": "处理数量与数据量",
        "stats.outcome_chart": "修复结果分布",
        "stats.daily_chart": "最近统计来源",
        "stats.daily_analyzed": "分析",
        "stats.daily_repaired": "修复",
        "stats.daily_scanned": "扫描",
        "stats.not_enough": "累计样本不足，图表会在分析更多图片后显示。",
        "stats.card.analysis": "累计分析",
        "stats.card.repair": "累计修复",
        "stats.card.skip_rollback": "跳过 / 回退",
        "stats.card.scan": "扫描来源",
        "stats.card.unsuitable": "不适合保留",
        "stats.card.similar": "相似组",
        "stats.card.failed_cancel": "失败 / 取消",
        "stats.card.issue_rate": "检出率",
        "stats.common_issues": "常见问题类型",
        "stats.images": "图片",
        "stats.candidate_images": "候选图片",
        "stats.groups": "累计分组",
        "stats.needs_attention": "需要关注",
        "stats.issue_images": "问题图 {count}",
        "stats.unsaved": "未保存 {count}",
        "stats.scan_rounds": "{count} 轮",
        "stats.skipped_folders": "跳过文件夹 {count}",
        "stats.analyzed": "分析图片",
        "stats.repaired": "修复图片",
        "stats.skipped": "跳过",
        "stats.scanned_files": "扫描文件",
        "meta.protected": "此项由软件保留",
        "meta.save": "保存修改",
        "meta.cancel": "取消",
        "meta.developer_required": "需要先开启高级编辑。",
        "meta.exiftool_required": "当前环境暂不支持写入此项。",
        "meta.field.title": "标题 / 描述",
        "meta.field.artist": "作者",
        "meta.field.copyright": "版权",
        "meta.field.keywords": "关键词 / 备注",
        "meta.field.image_unique_id": "图片唯一标识",
        "meta.field.user_comment": "用户备注",
        "meta.field.make": "相机品牌",
        "meta.field.model": "相机型号",
        "meta.field.lens_make": "镜头品牌",
        "meta.field.lens_model": "镜头型号",
        "meta.field.date_time": "文件时间",
        "meta.field.date_original": "拍摄时间",
        "meta.field.exposure_time": "曝光时间",
        "meta.field.f_number": "光圈值",
        "meta.field.iso": "ISO",
        "meta.field.focal_length": "焦距",
        "meta.field.gps": "GPS 摘要",
        "meta.field.gps_latitude": "GPS 纬度",
        "meta.field.gps_longitude": "GPS 经度",
        "meta.field.gps_altitude": "GPS 高度",
        "meta.field.xmp_title": "XMP 标题",
        "meta.field.xmp_description": "XMP 描述",
        "meta.field.xmp_creator": "XMP 作者",
        "meta.field.xmp_rights": "XMP 版权",
        "meta.field.iptc_keywords": "IPTC 关键词",
        "meta.field.iptc_caption": "IPTC 说明",
        "meta.field.iptc_credit": "IPTC 来源 / 署名",
    },
    "en_US": {
        "menu.language_quick": "Language",
        "menu.contact_author": "Contact Author",
        "help.faq": "FAQ",
        "help.contact": "Contact Author",
        "contact.title": "Contact Author",
        "contact.intro": "You can send the email template below, and add your own question or feedback.",
        "contact.email": "Email",
        "contact.template": "Email Template",
        "contact.extra": "Extra Notes",
        "contact.extra_placeholder": "Add what happened, what you expected, steps you tried, or how to contact you.",
        "contact.send": "Send Email",
        "contact.copy_template": "Copy Template",
        "contact.copy_email": "Copy Email",
        "contact.open_failed": "Could not open your mail app. Copy the template or email address and send it manually.",
        "contact.copied": "Copied to clipboard.",
        "contact.template_body": "Hello,\n\nI would like to report the following issue while using ShapeYourPhoto:\n\n1. What happened:\n2. Expected result:\n3. Steps I tried:\n4. System and version:\n\nThank you.",
        "settings.section.scan_rules": "Scan Ignore Rules",
        "settings.desc.scan_rules": "These rules apply to folder names only. Matching folders and images inside them are skipped; _repair is always kept out of scans.",
        "settings.rule.prefix": "Prefix",
        "settings.rule.suffix": "Suffix",
        "settings.rule.contains": "Contains",
        "settings.rule.prefix_desc": "Skip folders whose names start with a rule, such as _repair or _old.",
        "settings.rule.suffix_desc": "Skip folders whose names end with a rule, such as _backup or _old.",
        "settings.rule.contains_desc": "Skip folders whose names contain the rule text. Use carefully to avoid skipping normal albums.",
        "settings.rule.add": "Add",
        "settings.rule.multi_hint": "Use Ctrl or Shift to select multiple items, then delete them together.",
        "settings.rule.remove": "Remove Selected",
        "settings.rule.restore": "Restore Default",
        "settings.section.default_scan": "Default Scan Behavior",
        "settings.desc.default_scan": "When a folder contains subfolders, choose whether to ask each time or use a fixed scan mode.",
        "settings.default_scan_mode": "Default scan mode:",
        "settings.repair_summary_filter": "Default repair summary filter:",
        "settings.desc.future_tasks": "These options affect future tasks only. Existing analysis results are not changed.",
        "settings.section.concurrency": "Analysis Concurrency",
        "settings.desc.concurrency": "Controls how many images are analyzed at the same time. Auto is usually best; lower it if the computer feels busy.",
        "settings.concurrency_mode": "Concurrency mode:",
        "settings.concurrent_workers": "Simultaneous workers:",
        "settings.default_workers": "Current mode default: {count}",
        "settings.worker_range": "Allowed range: 1 to {max}",
        "settings.section.gpu": "GPU Acceleration",
        "settings.desc.gpu": "Use acceleration when available; otherwise ShapeYourPhoto safely uses CPU.",
        "settings.gpu_mode": "GPU acceleration:",
        "settings.gpu_hardware": "Hardware:",
        "settings.gpu_backend": "Acceleration:",
        "settings.gpu_detecting": "Checking...",
        "settings.gpu_reason_detecting": "Checking GPU hardware and available acceleration in the background.",
        "settings.gpu_available": "An acceleration backend is available; tasks will choose the stable available path.",
        "settings.gpu_hw_no_backend": "A GPU was detected, but this runtime has no usable acceleration backend. Copy diagnostics or open help for next steps.",
        "settings.gpu_cpu": "Tasks will continue on CPU.",
        "settings.gpu_check": "Check Again",
        "settings.gpu_copy": "Copy Diagnostics",
        "settings.gpu_help": "GPU Help",
        "settings.section.console": "Console Time Display",
        "settings.desc.console": "Choose how new Console log timestamps are shown.",
        "settings.console_time": "Time format:",
        "settings.desc.console_tz": "Use a timezone format when sharing logs across time zones.",
        "settings.section.appearance": "Appearance",
        "settings.desc.appearance": "Choose the color style you prefer.",
        "settings.theme": "Theme:",
        "settings.density": "UI density:",
        "settings.desc.density": "High detail slightly increases font size, row height, and button padding for 2K/4K or scaled displays.",
        "settings.section.language": "Interface Language",
        "settings.language": "Language:",
        "settings.section.version": "Current Version",
        "settings.version_id": "Version ID {id}",
        "settings.check_updates": "Check Updates",
        "settings.desc.update": "You can manually check for a new version at any time.",
        "settings.section.announcements": "Announcements",
        "settings.refresh_announcements": "Refresh Announcements",
        "settings.no_announcements": "No announcements.",
        "settings.refreshing_announcements": "Refreshing announcements...",
        "settings.fetching_announcements": "Fetching announcements.",
        "settings.announcement_retry": "Please try again later.",
        "settings.announcement_failed": "No announcement was available.",
        "settings.announcement_count": "Fetched {count} announcement(s).",
        "settings.need_prefix": "Keep at least one folder ignore prefix.",
        "settings.save_failed": "Save failed.",
        "settings.save_failed_title": "Save Failed",
        "settings.save_failed_body": "Could not save app settings:\n{error}",
        "settings.check_unavailable": "Update checks are not available from this window right now.",
        "settings.copied": "Copied to clipboard.",
        "option.scan.ask": "Ask each time",
        "option.scan.all": "Scan all, including subfolders",
        "option.scan.current_only": "Scan current folder only",
        "option.scan.subdirs_only": "Scan subfolders only",
        "option.summary.all": "All",
        "option.summary.repaired": "Repaired",
        "option.summary.skipped": "Skipped",
        "option.summary.failed": "Failed",
        "option.summary.forced_unsaved": "Forced attempt not saved",
        "option.summary.forced_saved": "Saved after forced attempt",
        "option.summary.discard_related": "Unsuitable-image related",
        "option.summary.rollback_noop": "Rolled back or not saved",
        "option.worker.auto": "Auto",
        "option.worker.low": "Low",
        "option.worker.medium": "Medium",
        "option.worker.high": "High",
        "option.worker.extreme": "Extreme",
        "option.worker.custom": "Custom worker count",
        "option.gpu.off": "Off",
        "option.gpu.auto": "Auto",
        "option.gpu.on": "On",
        "option.console.24h": "24-hour time [20:28:14]",
        "option.console.12h": "12-hour time [08:28:14 PM]",
        "option.console.24h_tz": "24-hour time + timezone [20:28:14 UTC+09:00]",
        "option.console.elapsed": "Elapsed since launch [T+00:20:28]",
        "option.density.standard": "Standard",
        "option.density.comfortable": "Comfortable",
        "option.density.high_detail": "High detail",
        "scan_dialog.title": "Choose Folder Scan Range",
        "scan_dialog.heading": "This folder contains subfolders. Choose the scan range.",
        "scan_dialog.folder": "Folder: {folder}",
        "scan_dialog.prefix": "Ignored prefixes: {values}",
        "scan_dialog.suffix": "Ignored suffixes: {values}",
        "scan_dialog.contains": "Name contains: {values}",
        "scan_dialog.none": "None",
        "scan_dialog.rule_note": "Folders matching these rules will be skipped, including images inside them.",
        "scan_dialog.all": "Scan All, Including Subfolders",
        "scan_dialog.all_desc": "Scan the current folder and all allowed subfolders.",
        "scan_dialog.current": "Scan Current Folder Only",
        "scan_dialog.current_desc": "Read only images directly inside the current folder.",
        "scan_dialog.subdirs": "Scan Subfolders Only",
        "scan_dialog.subdirs_desc": "Read only images inside subfolders.",
        "scan_dialog.cancel": "Cancel Scan",
        "stats.title": "Stats",
        "stats.subtitle": "Shows cumulative analysis, repair, skipped, rollback, unsuitable-image, and similar-group statistics.",
        "stats.export": "Export Report",
        "stats.export_title": "Export Stats Report",
        "stats.export_done": "Stats report exported to:\n{path}",
        "stats.close": "Close",
        "stats.issue_rate_chart": "Issue Rate Trend",
        "stats.volume_chart": "Processed Count and Data Size",
        "stats.outcome_chart": "Repair Outcome Distribution",
        "stats.daily_chart": "Recent Stat Sources",
        "stats.daily_analyzed": "Analyzed",
        "stats.daily_repaired": "Repaired",
        "stats.daily_scanned": "Scanned",
        "stats.not_enough": "More samples are needed before this chart appears.",
        "stats.card.analysis": "Analyzed",
        "stats.card.repair": "Repaired",
        "stats.card.skip_rollback": "Skipped / Rolled Back",
        "stats.card.scan": "Scan Sources",
        "stats.card.unsuitable": "Unsuitable",
        "stats.card.similar": "Similar Groups",
        "stats.card.failed_cancel": "Failed / Canceled",
        "stats.card.issue_rate": "Issue Rate",
        "stats.common_issues": "Common Issue Types",
        "stats.images": "images",
        "stats.candidate_images": "candidate images",
        "stats.groups": "groups total",
        "stats.needs_attention": "needs attention",
        "stats.issue_images": "{count} issue images",
        "stats.unsaved": "{count} not saved",
        "stats.scan_rounds": "{count} runs",
        "stats.skipped_folders": "{count} folders skipped",
        "stats.analyzed": "Analyzed images",
        "stats.repaired": "Repaired images",
        "stats.skipped": "Skipped",
        "stats.scanned_files": "Scanned files",
        "meta.protected": "Reserved by ShapeYourPhoto",
        "meta.save": "Save Changes",
        "meta.cancel": "Cancel",
        "meta.developer_required": "Enable advanced editing first.",
        "meta.exiftool_required": "This item cannot be written in the current environment.",
        "meta.field.title": "Title / Description",
        "meta.field.artist": "Author",
        "meta.field.copyright": "Copyright",
        "meta.field.keywords": "Keywords / Notes",
        "meta.field.image_unique_id": "Image Unique ID",
        "meta.field.user_comment": "User Comment",
        "meta.field.make": "Camera Make",
        "meta.field.model": "Camera Model",
        "meta.field.lens_make": "Lens Make",
        "meta.field.lens_model": "Lens Model",
        "meta.field.date_time": "File Time",
        "meta.field.date_original": "Date Taken",
        "meta.field.exposure_time": "Exposure Time",
        "meta.field.f_number": "Aperture",
        "meta.field.iso": "ISO",
        "meta.field.focal_length": "Focal Length",
        "meta.field.gps": "GPS Summary",
        "meta.field.gps_latitude": "GPS Latitude",
        "meta.field.gps_longitude": "GPS Longitude",
        "meta.field.gps_altitude": "GPS Altitude",
        "meta.field.xmp_title": "XMP Title",
        "meta.field.xmp_description": "XMP Description",
        "meta.field.xmp_creator": "XMP Creator",
        "meta.field.xmp_rights": "XMP Rights",
        "meta.field.iptc_keywords": "IPTC Keywords",
        "meta.field.iptc_caption": "IPTC Caption",
        "meta.field.iptc_credit": "IPTC Credit",
    },
    "ja_JP": {
        "menu.language_quick": "Language",
        "menu.contact_author": "作者に連絡",
        "help.faq": "よくある質問",
        "help.contact": "作者に連絡",
        "contact.title": "作者に連絡",
        "contact.intro": "下のメールテンプレートを送信し、必要に応じて質問やフィードバックを追加できます。",
        "contact.email": "メール",
        "contact.template": "メールテンプレート",
        "contact.extra": "補足",
        "contact.extra_placeholder": "発生した問題、期待した結果、試した操作、連絡先などを入力してください。",
        "contact.send": "メールを送る",
        "contact.copy_template": "テンプレートをコピー",
        "contact.copy_email": "メールをコピー",
        "contact.open_failed": "メールアプリを開けませんでした。テンプレートまたはメールアドレスをコピーして手動で送信してください。",
        "contact.copied": "クリップボードにコピーしました。",
        "contact.template_body": "こんにちは。\n\nShapeYourPhoto の使用中に、以下の件を報告したいです。\n\n1. 発生した問題：\n2. 期待した結果：\n3. 試した操作：\n4. システムとバージョン：\n\nよろしくお願いします。",
        "settings.section.scan_rules": "スキャン除外ルール",
        "settings.desc.scan_rules": "これらのルールはフォルダー名だけに適用されます。一致したフォルダーと中の画像はスキップされます。_repair は常に除外されます。",
        "settings.rule.prefix": "接頭辞",
        "settings.rule.suffix": "接尾辞",
        "settings.rule.contains": "含む",
        "settings.rule.prefix_desc": "_repair や _old など、名前がこの文字で始まるフォルダーをスキップします。",
        "settings.rule.suffix_desc": "_backup や _old など、名前がこの文字で終わるフォルダーをスキップします。",
        "settings.rule.contains_desc": "名前にこの文字を含むフォルダーをスキップします。通常のアルバムを誤って除外しないよう注意してください。",
        "settings.rule.add": "追加",
        "settings.rule.multi_hint": "Ctrl または Shift で複数選択し、一括削除できます。",
        "settings.rule.remove": "選択を削除",
        "settings.rule.restore": "既定に戻す",
        "settings.section.default_scan": "既定のスキャン動作",
        "settings.desc.default_scan": "サブフォルダーがある場合、毎回確認するか固定のスキャン方式を使えます。",
        "settings.default_scan_mode": "既定のスキャン方式：",
        "settings.repair_summary_filter": "修復完了詳細の既定フィルター：",
        "settings.desc.future_tasks": "これらの設定は今後のタスクだけに反映され、完了済みの分析結果は変更しません。",
        "settings.section.concurrency": "分析の同時処理",
        "settings.desc.concurrency": "同時に分析する画像数を制御します。通常は自動がおすすめです。重い場合は下げてください。",
        "settings.concurrency_mode": "同時処理モード：",
        "settings.concurrent_workers": "同時処理数：",
        "settings.default_workers": "現在の既定値：{count}",
        "settings.worker_range": "設定範囲：1 から {max}",
        "settings.section.gpu": "GPU アクセラレーション",
        "settings.desc.gpu": "利用できる場合はアクセラレーションを試します。利用できない場合は安全に CPU を使います。",
        "settings.gpu_mode": "GPU：",
        "settings.gpu_hardware": "ハードウェア：",
        "settings.gpu_backend": "アクセラレーション：",
        "settings.gpu_detecting": "確認中...",
        "settings.gpu_reason_detecting": "GPU ハードウェアと利用可能なアクセラレーションをバックグラウンドで確認しています。",
        "settings.gpu_available": "利用可能なアクセラレーションが見つかりました。タスクは安定した利用可能経路を選択します。",
        "settings.gpu_hw_no_backend": "GPU は検出されましたが、現在の実行環境に利用可能なアクセラレーションがありません。診断情報をコピーするか、ヘルプを確認してください。",
        "settings.gpu_cpu": "タスクは CPU で続行します。",
        "settings.gpu_check": "再確認",
        "settings.gpu_copy": "診断をコピー",
        "settings.gpu_help": "GPU ヘルプ",
        "settings.section.console": "Console 時刻表示",
        "settings.desc.console": "Console の新しいログ時刻の表示方式を選びます。",
        "settings.console_time": "時刻形式：",
        "settings.desc.console_tz": "タイムゾーンをまたぐ共有では、タイムゾーン付き形式が便利です。",
        "settings.section.appearance": "外観",
        "settings.desc.appearance": "好みの配色を選びます。",
        "settings.theme": "テーマ：",
        "settings.density": "表示密度：",
        "settings.desc.density": "高精細ではフォント、行高、ボタン余白が少し増えます。2K/4K や拡大表示に向いています。",
        "settings.section.language": "表示言語",
        "settings.language": "言語：",
        "settings.section.version": "現在のバージョン",
        "settings.version_id": "バージョンID {id}",
        "settings.check_updates": "更新を確認",
        "settings.desc.update": "いつでも新しいバージョンを手動で確認できます。",
        "settings.section.announcements": "お知らせ",
        "settings.refresh_announcements": "お知らせを更新",
        "settings.no_announcements": "お知らせはありません。",
        "settings.refreshing_announcements": "お知らせを更新中...",
        "settings.fetching_announcements": "お知らせを取得中です。",
        "settings.announcement_retry": "後でもう一度お試しください。",
        "settings.announcement_failed": "お知らせを取得できませんでした。",
        "settings.announcement_count": "{count} 件のお知らせを取得しました。",
        "settings.need_prefix": "フォルダー除外接頭辞を少なくとも 1 つ残してください。",
        "settings.save_failed": "保存できませんでした。",
        "settings.save_failed_title": "保存失敗",
        "settings.save_failed_body": "アプリ設定を保存できませんでした：\n{error}",
        "settings.check_unavailable": "このウィンドウからは現在、更新確認を開始できません。",
        "settings.copied": "クリップボードにコピーしました。",
        "option.scan.ask": "毎回確認",
        "option.scan.all": "すべてスキャン（サブフォルダーを含む）",
        "option.scan.current_only": "現在のフォルダーのみ",
        "option.scan.subdirs_only": "サブフォルダーのみ",
        "option.summary.all": "すべて",
        "option.summary.repaired": "修復済み",
        "option.summary.skipped": "スキップ済み",
        "option.summary.failed": "失敗",
        "option.summary.forced_unsaved": "強制試行・未保存",
        "option.summary.forced_saved": "強制試行後に保存",
        "option.summary.discard_related": "保留に向かない画像関連",
        "option.summary.rollback_noop": "回退または未保存",
        "option.worker.auto": "自動",
        "option.worker.low": "低",
        "option.worker.medium": "中",
        "option.worker.high": "高",
        "option.worker.extreme": "極高",
        "option.worker.custom": "同時処理数を指定",
        "option.gpu.off": "オフ",
        "option.gpu.auto": "自動",
        "option.gpu.on": "オン",
        "option.console.24h": "24 時間制 [20:28:14]",
        "option.console.12h": "12 時間制 [08:28:14 PM]",
        "option.console.24h_tz": "24 時間制 + タイムゾーン [20:28:14 UTC+09:00]",
        "option.console.elapsed": "起動後の経過時間 [T+00:20:28]",
        "option.density.standard": "標準",
        "option.density.comfortable": "ゆったり",
        "option.density.high_detail": "高精細",
        "scan_dialog.title": "フォルダーのスキャン範囲を選択",
        "scan_dialog.heading": "現在のフォルダーにはサブフォルダーがあります。スキャン範囲を選択してください。",
        "scan_dialog.folder": "フォルダー：{folder}",
        "scan_dialog.prefix": "除外接頭辞：{values}",
        "scan_dialog.suffix": "除外接尾辞：{values}",
        "scan_dialog.contains": "名前に含む：{values}",
        "scan_dialog.none": "なし",
        "scan_dialog.rule_note": "これらのルールに一致するフォルダーと中の画像はスキャンされません。",
        "scan_dialog.all": "すべてスキャン（サブフォルダーを含む）",
        "scan_dialog.all_desc": "現在のフォルダーと許可されたすべてのサブフォルダーをスキャンします。",
        "scan_dialog.current": "現在のフォルダーのみ",
        "scan_dialog.current_desc": "現在のフォルダー直下の画像だけを読み込みます。",
        "scan_dialog.subdirs": "サブフォルダーのみ",
        "scan_dialog.subdirs_desc": "サブフォルダー内の画像だけを読み込みます。",
        "scan_dialog.cancel": "スキャンを中止",
        "stats.title": "統計",
        "stats.subtitle": "累計分析、修復、スキップ、回退、保留に向かない画像、類似グループなどの統計を表示します。",
        "stats.export": "レポートを書き出す",
        "stats.export_title": "統計レポートを書き出す",
        "stats.export_done": "統計レポートを書き出しました：\n{path}",
        "stats.close": "閉じる",
        "stats.issue_rate_chart": "問題検出率の推移",
        "stats.volume_chart": "処理数とデータ量",
        "stats.outcome_chart": "修復結果の分布",
        "stats.daily_chart": "最近の統計ソース",
        "stats.daily_analyzed": "分析",
        "stats.daily_repaired": "修復",
        "stats.daily_scanned": "スキャン",
        "stats.not_enough": "サンプルが増えると、このグラフが表示されます。",
        "stats.card.analysis": "累計分析",
        "stats.card.repair": "累計修復",
        "stats.card.skip_rollback": "スキップ / 回退",
        "stats.card.scan": "スキャン元",
        "stats.card.unsuitable": "保留に向かない画像",
        "stats.card.similar": "類似グループ",
        "stats.card.failed_cancel": "失敗 / 中止",
        "stats.card.issue_rate": "検出率",
        "stats.common_issues": "よくある問題タイプ",
        "stats.images": "画像",
        "stats.candidate_images": "候補画像",
        "stats.groups": "累計グループ",
        "stats.needs_attention": "確認が必要",
        "stats.issue_images": "問題画像 {count}",
        "stats.unsaved": "未保存 {count}",
        "stats.scan_rounds": "{count} 回",
        "stats.skipped_folders": "スキップフォルダー {count}",
        "stats.analyzed": "分析画像",
        "stats.repaired": "修復画像",
        "stats.skipped": "スキップ",
        "stats.scanned_files": "スキャンファイル",
        "meta.protected": "ShapeYourPhoto が保持する項目です",
        "meta.save": "変更を保存",
        "meta.cancel": "キャンセル",
        "meta.developer_required": "先に高度な編集を有効にしてください。",
        "meta.exiftool_required": "現在の環境ではこの項目を書き込めません。",
        "meta.field.title": "タイトル / 説明",
        "meta.field.artist": "作者",
        "meta.field.copyright": "著作権",
        "meta.field.keywords": "キーワード / メモ",
        "meta.field.image_unique_id": "画像固有 ID",
        "meta.field.user_comment": "ユーザーコメント",
        "meta.field.make": "カメラメーカー",
        "meta.field.model": "カメラモデル",
        "meta.field.lens_make": "レンズメーカー",
        "meta.field.lens_model": "レンズモデル",
        "meta.field.date_time": "ファイル時刻",
        "meta.field.date_original": "撮影日時",
        "meta.field.exposure_time": "露出時間",
        "meta.field.f_number": "絞り値",
        "meta.field.iso": "ISO",
        "meta.field.focal_length": "焦点距離",
        "meta.field.gps": "GPS 概要",
        "meta.field.gps_latitude": "GPS 緯度",
        "meta.field.gps_longitude": "GPS 経度",
        "meta.field.gps_altitude": "GPS 高度",
        "meta.field.xmp_title": "XMP タイトル",
        "meta.field.xmp_description": "XMP 説明",
        "meta.field.xmp_creator": "XMP 作成者",
        "meta.field.xmp_rights": "XMP 権利",
        "meta.field.iptc_keywords": "IPTC キーワード",
        "meta.field.iptc_caption": "IPTC 説明",
        "meta.field.iptc_credit": "IPTC クレジット",
    },
}


for _lang, _values in _EXTRA_TEXT.items():
    TEXT.setdefault(_lang, {}).update(_values)


def tr(key: str) -> str:
    lang = normalize_language(get_current_language())
    return TEXT.get(lang, TEXT[DEFAULT_LANGUAGE]).get(key, TEXT[DEFAULT_LANGUAGE].get(key, key))
