from __future__ import annotations

APP_NAME = "Shape Your Photo"
APP_VERSION = "1.2.7"
APP_VERSION_ID = 11
APP_BUILD_ID = 11
APP_UPDATE_CHANNEL = "stable"
APP_ID = "helloalp.shapeyourphoto.desktop"

CHANGELOG_I18N: dict[str, list[dict[str, object]]] = {
    "en_US": [
        {
            "version": "1.2.7",
            "date": "2026-05-22",
            "items": [
                "The root ShapeYourPhoto.exe now performs silent native startup checks and opens the GUI without command prompt windows.",
                "Update history restores earlier 1.2.7 entries and all older versions after the root-folder cleanup.",
                "The startup splash is once again a centered compact logo panel, and the main window opens at 60% of the available screen by default.",
                "Display settings now include main-window and dialog-size controls, with dialogs opening smaller than the main window so the background stays visible.",
                "Appearance settings can now restore window layout defaults immediately, including the current main-window divider position.",
                "Analysis progress no longer stalls when the progress dialog refreshes, and cancel callbacks keep working even if one UI update fails.",
                "The main window close button now takes a high-priority shutdown path that requests running tasks to cancel and force-exits if worker threads keep the process alive.",
                "The Rust launcher now reads config/launch_manifest.json, prefers bundled Python runtime paths, supports diagnostic timing logs, and caches successful dependency health checks.",
                "Language resources can now live under locales/<locale>/<domain>.json while existing locale override files remain compatible.",
                "The app now has an AppContext service registry for settings, logging, language, theme, preview cache, task state, stats, update, and platform services.",
                "Scan, analysis, repair, format conversion, updater, and large-preview work now share one task-state vocabulary for running, canceling, completed, failed, and canceled outcomes.",
                "TaskManager now owns worker submission, run IDs, cancellation events, progress events, wrapped errors, task timing, and UI callback queues for long-running work.",
                "Rust migration guidance now favors native scan, similarity, metadata, repair scoring, update staging, and launcher health-check hot paths while keeping Tk orchestration in Python.",
                "Progress dialogs keep one clear progress bar, with duplicate lower progress lines removed.",
                "Unsuitable-image review cards can be selected by clicking the whole card area, and paged review shows more candidates per screen.",
                "Similar-image review wording is simplified from filter-specific labels to clearer Select All and Start Selection actions.",
            ],
        },
        {
            "version": "1.2.6",
            "date": "2026-05-16",
            "items": [
                "Startup now detects missing Python more clearly and can guide Windows users through a safe official install path.",
                "Legacy root-level files from older layouts are moved into an update quarantine report instead of being deleted.",
                "The right panel now uses peer tabs for Diagnosis, Preview, Properties / EXIF, and Console, with a larger adaptive image preview.",
                "Scan ignore rules now support folder-name prefixes, suffixes, and contains rules, with numbered lists and multi-select removal.",
                "Folder scanning now rejects file paths cleanly and the scan-range dialog shows every active ignore rule.",
                "Language settings now include Simplified Chinese, English, and Japanese, with multilingual update history support starting from v1.2.6.",
                "After saving a language change, the main window menus, toolbar buttons, filter list, table headings, right-side tabs, preview empty state, and settings-window frame update immediately.",
                "Saving settings now applies changes without closing the settings window, so users can keep adjusting options.",
                "GPU acceleration now uses a bundled Rust/wgpu native backend for large-image luma statistics, with automatic CPU fallback when the packaged component or adapter is unavailable.",
                "Large-image luma histogram, exposure ratios, and percentile statistics now run through the native GPU path when profitable, with actual acceleration recorded in performance logs.",
                "Repair candidate scoring, similar-image thumbnail features, and small-image tasks remain CPU-gated when benchmarks show CPU is faster, including iGPU-class scenarios.",
                "The Settings GPU actions now focus on recheck, native self-test, diagnostics, and logs; missing native components trigger automatic CPU fallback instead of asking users to run GPU requirements.",
                "Windows packaging and CI now build and verify the native GPU backend; requirements-gpu.txt was removed and the quick module index moved to docs/MODULES.md.",
                "The right-side preview redraws from the original image after layout settles and avoids repeated full decodes for ultra-high-resolution photos.",
                "The right-side large preview now decodes in the background and discards stale requests when users switch images quickly.",
                "List thumbnails now use a timestamp-aware LRU cache; cleanup-review and similar-review thumbnails decode JPEGs near their target size to reduce large-folder load and memory cost.",
                "Help now includes Contact Author and FAQ entries, with an email template, manual copy fallback, and multilingual text.",
                "Settings pages now scroll independently while Save, Cancel, and status stay fixed; the Language shortcut appears in non-English menus and opens the language page directly.",
                "Stats now records scan, skip, rollback, issue type, repair outcome, cancel, and performance sources, and the stats window shows richer summaries and charts.",
                "Repair cancel cleanup and rollback now finish in the background so the UI stays responsive.",
                "Batch conversion now shows progress, supports cancel rollback and finish-after-current, writes atomically, and preserves DPI/metadata where supported.",
                "Repair Current is now Repair Selected and only accepts selected files that are still in the current list and already analyzed.",
                "Repair candidate luma statistics can use the bundled native GPU backend and records actual acceleration or fallback in performance logs.",
            ],
        }
    ],
    "ja_JP": [
        {
            "version": "1.2.7",
            "date": "2026-05-22",
            "items": [
                "ルートの ShapeYourPhoto.exe は静かなネイティブ起動チェックを行い、コマンドプロンプトを出さずに GUI を開きます。",
                "ルートフォルダー整理後に失われていた 1.2.7 以前の更新履歴を復元しました。",
                "起動 Splash は中央の小さなロゴパネルに戻り、メイン画面は既定で使用可能な画面領域の 60% で開きます。",
                "表示設定でメイン画面とダイアログの大きさを調整でき、ダイアログはメイン画面より小さく開きます。",
                "進行状況ダイアログ更新時に分析が止まる問題を修正し、キャンセル操作も継続して動作します。",
                "メイン画面の閉じるボタンは優先度の高い終了経路になり、実行中タスクへ中止を要求したうえで、必要に応じてプロセス終了で確実に閉じます。",
                "Rust ランチャーは config/launch_manifest.json、同梱 Python runtime、診断用の起動時間ログ、依存関係チェックのキャッシュに対応しました。",
                "言語リソースは locales/<locale>/<domain>.json に分割でき、既存の上書きファイルも引き続き利用できます。",
                "settings、ログ、言語、テーマ、プレビューキャッシュ、タスク状態、統計、更新、プラットフォームサービスをまとめる AppContext サービスレジストリを追加しました。",
                "スキャン、分析、修復、形式変換、更新、大きなプレビューは、実行中、中止処理中、完了、失敗、中止済みを同じタスク状態語彙で扱います。",
                "TaskManager は長時間処理の worker 登録、run ID、中止イベント、進行状況、エラー、実行時間、UI コールバックキューをまとめて扱います。",
                "Rust 化の方針を更新し、スキャン、類似画像、metadata、修復スコア、更新 staging、ランチャー診断を優先候補にし、Tk の編成は Python 側に残します。",
                "進行状況ダイアログは重複した下部バーをなくし、1 本の見やすい進行バーに整理しました。",
                "保存に向かない画像の確認ではカード全体をクリックして選択でき、ページ切り替えで多くの候補を扱えます。",
                "類似画像確認の表記を Select All と Start Selection に相当する分かりやすい表現へ整理しました。",
            ],
        },
        {
            "version": "1.2.6",
            "date": "2026-05-16",
            "items": [
                "Python が見つからない場合の案内を改善し、Windows では公式の安全なインストール手順へ進めます。",
                "旧レイアウトのルート直下ファイルは削除せず、更新用の隔離フォルダーとレポートへ移動します。",
                "右側パネルを「診断」「プレビュー」「属性 / EXIF」「Console」の同列タブに整理し、大きな画像プレビューを追加しました。",
                "スキャンの除外ルールが、フォルダー名の前方一致、後方一致、部分一致に対応しました。番号付き一覧と複数選択削除も利用できます。",
                "ファイルのパスをフォルダーとしてスキャンしようとした場合は安全に案内し、スキャン範囲ダイアログには有効な除外ルールをすべて表示します。",
                "言語設定に簡体中文、English、日本語を追加し、v1.2.6 以降の更新履歴を多言語表示できる構造にしました。",
                "言語変更を保存すると、メニュー、上部ボタン、フィルター、一覧見出し、右側タブ、プレビューの空状態、設定ウィンドウ枠がすぐに更新されます。",
                "設定を保存しても設定ウィンドウを閉じず、変更をすぐ適用したまま続けて調整できます。",
                "GPU 状態は、ハードウェアの検出、加速準備状況、現在のタスク使用状況を区別し、準備できていない場合は CPU に安全に戻ります。",
                "右側プレビューはレイアウト確定後に元画像から再描画し、超高解像度写真の不要なフルデコード反復を避けます。",
                "右側の大きなプレビューはバックグラウンドでデコードし、画像を素早く切り替えた場合は古い要求を破棄します。",
                "一覧サムネイルは更新時刻を含む LRU キャッシュを使い、削除候補レビューと類似画像レビューのサムネイルも表示サイズに近い解像度で JPEG を読み込みます。",
                "ヘルプに作者への連絡と FAQ を追加し、メールテンプレート、コピーによる代替手段、多言語表示に対応しました。",
                "設定ページは各ページ内でスクロールし、保存・キャンセル・状態表示は固定されます。英語以外では `Language` ショートカットから言語ページを直接開けます。",
                "統計はスキャン、スキップ、回退、問題タイプ、修復結果、中止、性能ソースを記録し、統計ウィンドウの要約とグラフを拡張しました。",
                "修復キャンセル時の清理と回退はバックグラウンドで完了し、UI の応答性を保ちます。",
                "一括形式変換は進捗、キャンセル時の回退、現在分で終了、原子的な保存、対応形式での DPI / メタデータ保持に対応しました。",
                "「現在の画像を修復」は「選択を修復」になり、現在の一覧に残っていて分析済みの選択ファイルだけを処理します。",
                "修復候補の輝度統計も bundled native GPU backend を利用でき、実際の加速または fallback を性能ログに記録します。",
            ],
        }
    ],
}

CHANGELOG: list[dict[str, object]] = [
    {
        "version": "1.2.7",
        "date": "2026-05-22",
        "items": [
            "根目录 ShapeYourPhoto.exe 改为静默完成原生启动检查并直接打开主界面，不再弹出多个命令提示符窗口。",
            "恢复设置更新历史中的 1.2.7 早期记录和 1.2.6 及更早版本记录，避免根目录整理后历史缺失。",
            "启动 Splash 恢复为居中的小块 Logo 背景，不再被放大成大面积白色窗口；主窗口默认以屏幕可用区域 60% 打开。",
            "设置页新增主窗口初始大小和弹窗默认大小调节项，弹窗默认小于主界面并保留背景可见。",
            "设置页外观 / 风格新增“恢复窗口布局默认值”，点击后立即保存窗口布局默认值，并让主窗口分隔条立刻归位。",
            "窗口布局默认值集中到同一处维护，主窗口、弹窗和可拖动分隔条不再分散硬编码默认尺寸。",
            "修复分析进度窗口刷新时导致分析停滞的问题，取消按钮和后续任务回调恢复正常。",
            "UI 回调队列增加异常隔离，单个界面刷新失败会写入 Console，不再阻断进度、取消和完成回调。",
            "主窗口关闭按钮升级为高优先级关闭路径，会先请求运行中任务取消，必要时用进程级退出确保程序关闭。",
            "Rust 启动器新增 config/launch_manifest.json、内置 Python runtime 优先解析、诊断模式毫秒级阶段耗时日志和依赖健康检查缓存。",
            "多语言资源可按 locales/<locale>/<domain>.json 拆分维护，并继续兼容既有语言覆盖文件。",
            "新增 AppContext 服务 registry，集中承载 settings、Console、i18n、theme、preview cache、task manager、stats、update 和 platform services。",
            "扫描、分析、修复、格式转换、更新器和大图预览接入统一任务状态语义，取消、收尾、完成、失败和写回防护使用同一套状态词汇。",
            "TaskManager 升级为统一耗时任务入口，集中管理 worker 提交、run_id、取消信号、进度事件、错误封装、任务耗时和 UI 回调队列。",
            "Rust 原生化策略更新：扫描、相似图、metadata、修复评分、更新 staging 和启动器健康检查优先评估 Rust，Tk 编排继续留在 Python。",
            "分析、修复进度框去除重复的下方进度线，只保留上方主进度条。",
            "不适合保留图片复核改为点击整张卡片即可选择，并支持分页显示更多候选。",
            "相似图片复核文案从“全选当前筛选”“开始抉择”调整为“全选”“开始选择”。",
            "新增统一弹窗创建流程，核心弹窗统一处理隐藏布局、尺寸限制、居中显示和非阻塞窗口行为。",
            "新增文件安全服务，格式转换、EXIF 写入和回滚清理统一记录操作并使用事务备份或隔离目录。",
            "设置页扫描忽略规则默认列出 _repair、fmt_output 与 .metadata-bak；可按需要删除、恢复默认或补充规则。",
            "主界面导入、分析和格式转换入口移至顶部图形按钮，分析只处理当前已选标记图片，部分选择时会先确认。",
            "主界面修复入口移至顶部图形按钮，移除旧的纯文字修复行和左下角批量状态按钮；修复只处理列表状态为已选且已有有效分析与修复方案的图片。",
            "文件列表提示移入标题行，底部重复状态行移除，文件列表和右侧信息区会自然扩展。",
            "EXIF 与 GPS 编辑改为后台读取和保存，避免元数据解析、备份或写入阻塞主界面。",
            "Windows 拖入图片注册覆盖 Tk 内容窗口和外层 frame 窗口，并在窗口重新映射时刷新注册，提升拖入可靠性。",
            "窗口尺寸变化时会在布局稳定后再刷新预览与诊断图表，减少缩放过程中的黑块、遮挡和错位；顶部操作图标统一为同尺寸图形资源。",
            "主界面移除常驻不适合保留列表和清理勾选入口，复核弹窗与安全删除流程继续保留。",
            "相似图组选择列表支持点击整块条目、缩略图、文件名或空白区域切换选中状态；开始比较时会关闭组选择窗口。",
            "相似图结果页合并全选和取消全选按钮，按钮文字会按当前可见选择状态动态变化。",
            "同名不同路径图片会在列表名旁显示提示标记，鼠标悬停可查看真实路径。",
            "EXIF 保存默认不再保留可见 .metadata-bak 备份，可在行为偏好中手动开启。",
            "更新器新增跨版本保护：落后过多时阻止内置一键更新，并引导前往官网下载全新版本。",
            "新增结构化更新历史源文件和本地同步检查脚本，避免应用内更新历史与公开文档漂移。",
        ],
    },
    {
        "version": "1.2.6",
        "date": "2026-05-16",
        "items": [
            "高对比主题、窗口安全边距、设置页底栏、扫描范围窗口和分析进度计数继续增强，进度窗口显示图片数而不是内部阶段步数。",
            "主界面入口整理：官网移入帮助菜单，统计移入查看菜单，更新历史移入设置的更新页，并新增日志管理与日志导出。",
            "新增批量质量保持格式转换和 GPS 经纬度编辑入口，转换会尽量保留 EXIF 与方向，GPS 写入会备份并失败回退。",
            "批量格式转换增加可见进度、取消回滚、提前结束、临时文件原子写入、DPI/EXIF/方向保留和 Converted by ShapeYourPhoto 元数据来源标记。",
            "主界面“修复当前”改为“修复选中”，修复目标必须仍在当前列表内且已有分析结果，移出列表或未分析目标不会进入修复流程。",
            "修复取消会等待后台 worker 退出并显示回滚进度，完成输出清理或覆盖回滚后才恢复其他功能入口。",
            "GPU 加速改为应用自带 Rust/wgpu native backend，大图分析亮度统计会实际调用 GPU；极高并发策略对高线程 CPU 更积极但保留系统余量。",
            "修复候选亮度统计也会在合适的大图场景调用 native GPU backend，并在性能日志记录实际加速或 fallback。",
            "大图分析的亮度直方图、曝光比例和百分位统计已接入 GPU，性能日志会记录实际加速状态；修复候选评分、相似图缩略特征和小图任务按 benchmark 结果继续 CPU 门控。",
            "设置页 GPU 操作改为重新检测、native 自检、复制诊断和日志入口；native 组件缺失时显示安装包组件缺失并自动回退 CPU，不再要求普通用户运行 GPU requirements。",
            "Windows 打包和 CI 会构建并验证 native GPU backend；根目录删除 requirements-gpu.txt，模块索引移动到 docs/MODULES.md。",
            "相似图算法拆分近重复与同场景候选，降低连续编号权重，增强自然重复纹理和横竖构图差异的保守判定，低置信 pair 不再轻易扩组。",
            "主界面任务进度区接入扫描、分析和修复状态，文件夹扫描不再额外弹出扫描进度窗口，并支持取消后保留已找到的图片。",
            "UI 回调队列增加单次处理预算，进度窗口减少同步刷新开销，降低批量分析和修复期间点击主窗口时的卡顿风险。",
            "拖入图片和文件夹时会过滤不可读取文件；拖入单张、多张图片或文件夹后会立即加入列表或开始扫描，并在 Console 记录摘要。",
            "文件列表支持 Ctrl+A 全选、反选、清除选择、Delete/右键批量移出，批量修复仍只把真正多选或勾选集合视为批量目标。",
            "扫描、导入和列表刷新不再整批清空缩略图缓存，减少重复解码；扫描、分析、修复继续输出简短耗时摘要。",
            "GPU 状态说明改为区分硬件可见、加速组件准备情况和当前任务使用状态；加速组件未准备时会安全使用 CPU，并提供可理解的下一步入口。",
            "启动脚本在缺少 Python 时会识别 Windows 环境和可用安装方式，保留窗口并引导安装；运行前会把旧布局根目录残留文件移入隔离目录并生成清单。",
            "右侧信息区改为同级标签页：诊断、预览图、属性 / EXIF 和 Console；预览图页会随窗口尺寸显示更大的当前图片。",
            "查看菜单新增最近修复摘要，顶部菜单新增帮助与官网入口；修复完成详情、相似图和清理窗口默认尺寸更适合 1080p、2K 与 4K 屏幕。",
            "设置页新增界面清晰度 / 密度选项，并扩展语言偏好为简体中文、English、日本語；1.2.6 起更新历史支持按当前语言显示。",
            "切换语言并保存后，主窗口菜单、顶栏按钮、筛选下拉、列表/清理表头、右侧标签页、预览空状态和设置窗口框架会立即刷新。",
            "扫描忽略规则从单一前缀扩展为前缀、后缀、包含三类文件夹名称规则，列表显示序号，支持多选删除，并继续强制保护 _repair 输出目录。",
            "扫描入口会在路径栏为图片文件时提示重新选择文件夹，不再把文件路径传入目录遍历；扫描范围弹窗同步显示前缀、后缀和包含三类忽略规则。",
            "设置页点击“保存设置”后不再关闭窗口，设置会立即应用并允许继续调整；GPU 状态说明会区分硬件可见和运行后端缺失，并提供可选依赖入口。",
            "右侧预览图首次显示会等待布局稳定后用原图重新生成大图预览，并按显示区域降采样解码与缓存渲染尺寸，避免超高清图片选择时重复完整解码造成卡顿。",
            "右侧大图预览改为后台解码并丢弃过期请求，快速连续点选超高清图片时主界面不再等待完整预览解码。",
            "主列表缩略图缓存改为带文件时间戳的 LRU；不适合保留复核和相似图复核的缩略图生成会按目标尺寸降采样读取 JPEG，降低大文件夹首次加载、长时间浏览和复核窗口打开时的解码与内存压力。",
            "帮助菜单新增联系作者和常见问题入口；联系窗口提供发送邮件、复制模板、复制邮箱和补充说明输入。",
            "设置页改为每个页签独立滚动，底部保存、取消和状态区固定可见；非英语界面下顶部新增固定英文 Language 快捷入口并直达语言页。",
            "统计存储与统计窗口增加扫描、跳过、回退、问题类型、修复结果、取消和性能趋势等来源与图表。",
            "性能设置新增极高并发模式，并显示当前模式默认处理量和本机允许范围；自定义数量会按运行时上限限制。",
            "EXIF 编辑增加更多可编辑文本项，并在显示和保存层同时保护含 ShapeYourPhoto 常见变体的元数据。",
            "新增 Forest Mist、Clear Sky、Rose Gray 配色；右侧信息区滚动条更贴近边缘。",
            "分析与修复新增局部高光、局部暗部、灰雾低通透、天空/水面风景和绿植相关方向，并进入建议、修复计划、显示名和统计。",
            "修复取消时的输出清理和覆盖回滚改为后台收尾，修复引擎在关键阶段响应取消请求，避免主窗口无响应。",
        ],
    },
    {
        "version": "1.2.5",
        "date": "2026-05-12",
        "items": [
            "应用身份改为 helloalp.shapeyourphoto.desktop，Windows 任务栏 AppUserModelID、版本历史和正式文档不再暴露开发工具或上游 AI 名称。",
            "确认用户数据目录继续使用 Helloalp/ShapeYourPhoto，设置、统计、窗口图标和云端更新链路不依赖旧身份串。",
            "Windows 源码包统一为双击 start.bat 启动：自动检查 Python 和运行依赖，缺少依赖时按需安装，依赖齐全时直接打开主程序。",
            "源码包需要 Python 运行环境；start.bat 会保留提示窗口并给出下一步说明。",
            "根目录收敛为启动器、说明和依赖文件，应用代码移入 src/，旧启动脚本与 benchmark 工具移入 tools/。",
            "完成 src/ 迁移收口检查：旧内层代码目录不再存在，app.py、app.pyw、start.bat、launcher、benchmark、build、updater/cloud 相关入口均指向当前 src/ 布局。",
            "应用设置 schema 增加 language 字段，默认 zh_CN，并通过 src/ui/language.py 管理当前语言状态。",
            "src/ui/display_names.py 改为按当前语言返回内部 code/enum 显示名，补齐 en_US 显示映射；业务存储和判断仍保留英文内部值。",
            "设置页新增语言偏好保存逻辑；更新页只显示 Shape Your Photo vX.Y.Z 和版本 ID，不再展示构建 ID、更新 URL、公告 URL 或自动管理说明。",
            "设置页移除开发者模式入口，继续保留底层开发者能力边界，不在普通设置流程暴露实现入口。",
            "不适合保留复核、EXIF 编辑、主文件列表、扫描范围/进度、统计、修复完成摘要和更新/公告失败提示进一步改成面向用户的中文文案；详细错误继续写入 Console。",
            "新增 docs/specs/USER_FACING_LANGUAGE.md，并补充 Console 可读性和 display mapping 规范；本轮仍不做全局硬编码文案替换。",
            "应用内更新历史改为版本分组和编号列表展示，不再把 Markdown 符号直接显示给用户。",
            "不适合保留图片复核窗口新增选中详情区和横向滚动，主要原因、严重程度和状态均使用中文显示。",
            "主窗口右上角新增“置顶”按钮，点击后可让主窗口保持在普通窗口上方，再次点击取消。",
            "更新检查和独立 updater 请求统一使用 ShapeYourPhoto User-Agent；网络或 TLS 超时时显示简短中文失败提示，设置窗口和主界面仍可继续操作。",
            "独立 updater 的取消按钮和关闭叉号改为立即关闭 updater，不再显示“下一个安全点退出”之类的等待提示；下载阶段增加更长读取超时和多次重试。",
            "独立 updater 在更新包大小或 sha256 校验失败时输出 expected/actual/url 细节，并先切换为可关闭状态再显示失败提示；package_size 不一致但 sha256 正确时会继续更新。",
            "updater 自身进入 managed_files 时改由临时 stager 在当前 updater 退出后完成最后替换，降低自更新中途损坏风险。",
            "新增 src/updater_bootstrap.py 与 src/updater_v2.py，主程序优先启动新版 bootstrap；新版客户端支持 external_download_only / disable_in_app_update 类型 manifest，只展示说明并阻止内置 updater 启动。",
            "更新 manifest 预留目标版本范围筛选，支持 target_min_version_id / target_max_version_id 和未来的 updates 多候选列表，避免特定旧版本的手动下载提示误伤较新客户端。",
            "新增 tools/update_smoke/update_resilience_smoke.py，模拟验证版本比较、UA、网络超时、取消、校验错误、zip-slip、自更新、删除不存在路径、替换失败和回滚场景。",
        ],
    },
    {
        "version": "1.2.4",
        "date": "2026-05-11",
        "items": [
            "作为云端 updater 链路测试版本发布，验证 1.2.3 到 1.2.4 的更新检测、下载、校验和替换流程。",
        ],
    },
    {
        "version": "1.2.3",
        "date": "2026-05-11",
        "items": [
            "收紧启动云端检查顺序：自动更新提示和云端公告改为排队显示，避免并行弹窗抢占输入。",
            "确认旧版 1.2.1 卡住来自云端更新提示和公告同时命中旧弹窗实现；新版继续保留可见后再 grab 的弹窗修复。",
        ],
    },
    {
        "version": "1.2.2",
        "date": "2026-05-11",
        "items": [
            "修复启动后云端公告和自动更新弹窗可能锁住主界面输入的问题。",
            "云端公告已读后不再重复弹出，公告中的更新入口会先关闭公告再检查更新。",
        ],
    },
    {
        "version": "1.2.1",
        "date": "2026-05-11",
        "items": [
            "关闭流程不再显示 Closing 文案。",
            "主界面“作者官网”按钮改名为“官网”。",
        ],
    },
    {
        "version": "1.2.0",
        "date": "2026-05-10",
        "items": [
            "将 cryptography 纳入正式依赖安装流程，确保 Ed25519 manifest 验签不再依赖手工临时安装。",
            "内置 assets/update_public_key.pem 作为正式更新公钥来源，保留 SHAPEYOURPHOTO_UPDATE_PUBLIC_KEY_FILE 作为开发测试覆盖方式。",
            "优化缺少 cryptography 时的错误提示，明确提示运行 setup_deps.bat 或手动安装依赖，并区分本地依赖缺失与服务器签名失败。",
            "补齐 PyInstaller 打包配置中的 cryptography 验签模块，确保 Windows/macOS 发布包包含更新验签能力。",
            "修正 updater 部署和测试文档中的启动入口、公钥接入、固定 URL 与 1.2.0 到 1.2.1 真实更新链路测试流程。",
        ],
    },
    {
        "version": "1.1.9",
        "date": "2026-05-10",
        "items": [
            "Console 时间格式新增带时区的时间戳选项，便于跨地区排查日志。",
            "主界面“分析全部”按钮改为普通按钮样式，不再使用加粗强调。",
            "更新 manifest 与云端消息地址改为客户端内部固定地址，不在设置页公开显示或写入普通设置 JSON。",
            "配色方案设置页只展示配色名称，不再公开具体颜色 token。",
            "设置页更新区域只显示当前版本名称和版本 ID，保留手动检查更新按钮，不再展示构建 ID。",
            "设置页说明文案改为面向用户的简短描述，减少实现细节。",
            "主窗口标题改为 Shape Your Photo | v1.1.9 | by Helloalp。",
            "README 改为快速启动入口，并引导到 docs 查看维护规则，移除过时安装和自动打包说明。",
        ],
    },
    {
        "version": "1.1.8",
        "date": "2026-05-10",
        "items": [
            "EXIF 编辑升级为普通安全字段与本次运行有效的开发者高级字段两层。",
            "任何元数据值包含 shapeyourphoto 的字段都视为 ShapeYourPhoto 溯源字段并锁定，不允许普通或高级编辑绕过。",
            "右侧 HUD、诊断条图、风险值、百分比和数字区域预留固定列宽，避免遮挡与重叠。",
            "设置页新增更新、云端公告和开发者模式入口，并统一接入 app_settings.py 与 settings_dialog.py。",
            "新增签名更新检查、云端公告、本地状态 HMAC、模块完整性检查和独立 updater。",
            "启动和关闭流程改为居中 Splash 顺序，主界面新增作者官网按钮。",
            "明确版本记录编写规范：app_metadata.CHANGELOG、根 CHANGELOG 和 docs/updates 默认使用中文书写，内部 code/enum/storage 名称保持英文。",
        ],
    },
    {
        "version": "1.1.7",
        "date": "2026-05-10",
        "items": [
            "融合 main 已合入的跨平台打包、拖放、用户数据目录迁移与平台检测修复，并重新叠回 backup-v1.1.7-before-pr 的 UI、设置、统计和修复取消能力。",
            "保留 macOS .dmg / Windows Inno Setup 打包链路、GitHub Actions Release 发布、assets/app_icon.icns、build/ 配置和 README 安装说明。",
            "保留 dnd_support.create_root() 跨平台根窗口选择、Windows 原生拖放、macOS/Linux tkinterdnd2 拖放和 Tcl splitlist 路径解析。",
            "新增跨平台桌面打包：macOS 输出 .dmg（Apple Silicon 原生），Windows 输出 Inno Setup 安装程序；GitHub Actions 双 runner 并行构建并自动发布到 Releases。",
            "拖拽实现改为按平台分派：Windows 复用原生 ctypes 实现，macOS / Linux 改用 tkinterdnd2，根窗口由 dnd_support.create_root() 统一选择。",
            "用户配置与统计文件迁移到系统标准用户数据目录（macOS: ~/Library/Application Support/ShapeYourPhoto/，Windows: %APPDATA%/Helloalp/ShapeYourPhoto/），首次启动自动从旧 cwd 迁移；卸载不删除。",
            "drag_drop.py / desktop_integration.py / window_layout.py / file_actions.py / ui_repair_actions.py / watermark_signature.py 全部加 sys.platform 守卫，非 Windows 平台不再 import-time 崩溃。",
            "watermark_signature.py 字体策略升级：优先打包内字体，macOS 走 PingFang，Windows 走 Microsoft YaHei，Linux 走 Noto Sans CJK，避免默认字体不支持中文导致水印变方块。",
            "新增 paths.resource_path() / user_data_dir() / migrate_legacy_file() 工具，支撑 PyInstaller _MEIPASS 资源加载与跨平台数据目录。",
            "本轮不改变分析算法、修复风格、UI 主交互逻辑或用户数据处理规则。",
            "修正修复批次计时口径：Console 和修复完成详情以 total_wall_time 作为“本轮修复总耗时”，worker_cumulative_time 明确标注为并发 worker 累计耗时，不再把每张图 repair_total 相加当作用户等待时间。",
            "统一性能摘要命名：同时展示 total_wall_time、worker_cumulative_time、average_wall_time_per_image 和 average_worker_time_per_image，分析审计行也改用 total_wall_time 命名。",
            "修复进度弹窗底部布局：尺寸提示和取消按钮分列固定，初始高度按屏幕可用高度钳制，避免分析/修复过程中取消按钮被长文案挤走、遮挡或不可点击。",
            "修复进度窗口新增“取消修复”，窗口关闭叉号与按钮走同一 cancel_event；后台进度、结果和最终摘要写回前校验 repair run_id/cancel_event。",
            "实现修复取消回滚：取消后恢复修复前分析状态快照，保留原有 AnalysisResult、issues、推荐方法、cleanup/similar 状态，不弹正常完成详情，不更新本轮修复统计或调试打开列表。",
            "取消修复会清理已写出的非覆盖输出；删除失败时移入 _repair_canceled_outputs 并提示。覆盖原文件修复会先创建 _repair_cancel_backups，取消时恢复，正常完成后清理备份。",
            "应用设置新增 Console 页和外观/风格页：Console 支持 24 小时制、12 小时制、启动后经过时间；外观支持经典清绿、石墨灰、影像蓝、暖白纸和高对比五套主题 token。",
            "Windows 启动阶段启用 DPI awareness、Tk scaling 和系统字体配置，并新增居中 Splash，减少 4K/高缩放环境下系统拉伸导致的字体模糊。",
            "主界面移除顶部重复任务进度栏，扩展目录路径长栏，列表标题区展示分析统计，右侧 HUD/问题强度条图获得更高布局权重。",
            "移除主界面“读取目录”和“导出清理清单”入口；选择目录、拖入目录和分析前补扫描继续走统一扫描范围、进度弹窗和扫描摘要。",
            "目录扫描后新增“正在加载图片”阶段提示；Console 只记录扫描摘要，完整跳过目录明细进入扫描摘要窗口。",
            "二级窗口标题统一为 ShapeYourPhoto v.x.x.x - 功能名；修复完成详情摘要区压缩为 chip 信息条。",
            "新增显示名映射层，内部存储值保持不变，UI 对问题、场景、人像、曝光、色彩、修复方法、状态、worker/GPU/扫描/Console 时间模式和性能阶段做用户语言展示。",
            "统计持久化迁移到 data/usage_stats.dpapi，Windows 使用用户级 DPAPI 加密；旧 usage_stats.json 成功迁移后保留 migrated 备份，不直接删除。",
            "统计持久化继续写入系统用户数据目录；Windows 使用 usage_stats.dpapi + DPAPI，非 Windows 回落到用户数据目录内 JSON，旧 usage_stats.json 迁移后保留 migrated 备份。",
            "属性 / EXIF 页面新增安全编辑入口，只允许写入标题/描述、作者、版权、关键词/备注，保存前备份，禁止修改相机/镜头/拍摄时间/Orientation/ICC/内部标记。",
            "新增 ui/ 包承载窗口标题、显示名映射、主题、HiDPI、Splash 和 EXIF 编辑等 UI 基础设施，并建立 docs/specs/ 产品规范目录。",
            "修复 drag_drop.py 融合后的缩进错误，避免 WindowsFileDropTarget 在 import 阶段触发 NameError 导致 start_app 无窗口。",
            "更新 README、CHANGELOG、app_metadata.CHANGELOG 和 docs/updates/1.1.7.md，使 main 修改与本地修改都进入 1.1.7 版本记录。",
        ],
    },
    {
        "version": "1.1.6",
        "date": "2026-05-08",
        "items": [
            "重整正式文档体系：明确根 README、docs/MODULES.md、docs、docs/technical 与 docs/updates 的分工，并给出后续维护阅读顺序。",
            "重写系统总览、模块参考、UI 工作流、维护指南和文档保留规则，改为 1.1.6 当前维护口径。",
            "新增分析流水线、性能与并发、相似图片、不适合保留图片、设置与扫描等技术专题文档。",
            "修正旧内容误导：独立单图窗口、孤立“去噪当前”入口、普通 messagebox 承载批量长修复详情都不是当前主路径。",
            "补齐性能计时、benchmark、GPU fallback、相似图、cleanup、取消分析、设置、扫描和修复完成详情的维护规则。",
            "新增 docs/updates/1.1.6.md，并同步 CHANGELOG 与应用内版本历史。",
            "清理临时编译缓存，并修正 GPU 状态提示中的过时版本号；本轮不改变分析算法、修复风格、UI 主交互逻辑或用户数据处理规则。",
            "benchmark_test_images.py 新增本地自动报告：运行后写入被忽略的 benchmark_reports/，包含 JSON/Markdown 报告、慢阶段/慢图片 top 5、核心计数和与上一份报告的简单对比。",
            "app_settings.py 新增 settings_schema_version 与 migrate_settings() 迁移入口；旧设置、缺字段、错误类型、未知字段和损坏 JSON 都会安全规范化或回退默认值。",
            "test/README.md 补充本地样张命名与标注方式，新增 test/manifest.example.json；真实 manifest、真实图片和 benchmark 报告继续不提交。",
            "UI 主类拆分：ui_app.py 保留主窗口装配和高层协调，扫描、分析、修复、主列表、Console/perf、cleanup/similar 复核拆入独立 ui_* mixin 模块；不改变用户行为、分析算法或修复风格。",
            "修复“批量修复勾选”目标集合语义：真正多选优先，其次使用勾选集合；单个蓝色高亮行只用于“修复当前”，不再把批量目标错误缩成 1 张。",
            "修复准备窗口在多图时显示批量说明和方法汇总，强调逐张生成独立修复计划；批量修复仍按每张图自己的分析结果、方法、力度、候选评分和回退决策执行。",
            "稳定分析/修复进度弹窗内部布局：固定标题、说明、进度条、计数/耗时、阶段摘要和底部按钮区，长阶段文本压缩显示，避免控件跳动、重叠或重复取消入口观感。",
            "主要弹窗补齐最小尺寸与统一最小尺寸提示，修复完成详情窗口修正伸缩权重，保证列表/详情滚动且底部按钮可达。",
        ],
    },
    {
        "version": "1.1.5",
        "date": "2026-05-07",
        "items": [
            "批量分析取消路径小修：取消后保留文件列表，清空本轮已写入的分析结果/错误/cleanup 标记/相似组标记，旧后台回调继续通过 run_id 拒绝写回，用户可立即重新分析。",
            "Console 增加分析取消摘要：记录取消时已耗时、目标数量、清空结果/错误数量、取消数量，并在 worker 收尾后补充提交数、停止前完成数、丢弃结果数和后台停止等待耗时。",
            "基于项目根目录 /test 真实样张建立本地性能基准：图片文件继续忽略不入库，仅保留 README 说明；新增 benchmark_test_images.py，可在 /test 为空时安全跳过。",
            "修正 Console 性能统计口径：用户摘要以真实 wall time 为主，worker_cumulative_time 明确标注为并发 worker 单图耗时累计，不再用 total_analysis_time / average_time_per_image 误导用户。",
            "分析 worker 设置改为集中解析，low / medium / high / custom 会输出设置值、请求 worker 数、实际 worker 数和限制原因，并真正影响 ThreadPoolExecutor。",
            "大图分析改为受控 working image 路径：保留原图尺寸和区域坐标回写，基础统计、颜色、人像和质量阶段不再对全部指标使用原始超大数组；噪点分数按 working image 像素尺度校正以保持结论稳定。",
            "相似图特征提取对 JPEG 使用 Pillow draft 降低解码尺寸，继续复用原有感知哈希和相似组判断逻辑，不改变相似图结论风格。",
            "修复相似图片组内对比窗口默认高度不足时每图“删除此图”按钮可能被遮挡的问题：图片区改为独立可滚动区域，底部“跳过本组 / 跳过所有剩余组 / 结束选择”操作区固定在窗口底部，并按屏幕尺寸限制默认窗口大小。",
            "补齐分析与修复阶段耗时摘要：分析记录读取图片、基础统计、场景判断、人像/清晰度/噪声/色彩判断、不适合保留图片与相似图检测耗时；修复记录生成方案、读取图片、执行修复步骤、候选评分/安全检查、保存输出和元数据保留耗时。",
            "降低 Console 高频刷新开销：后台任务仍可记录完整状态，但 UI 文本框改为短延迟合并刷新，减少多线程分析/修复时 Tk 主线程被日志重绘拖慢。",
            "新增批量性能审计：Console 在分析结束时输出 total_analysis_time、total_wall_time、total_worker_time、average_time_per_image、queue/wait、最慢图片 top 5、最慢阶段 top 5、相似图检测、UI 刷新与 Console 刷新耗时。",
            "应用设置新增分析并发模式（自动/低/中/高/自定义 worker 数）与 GPU 加速选项（关闭/自动/开启）；加速组件未准备或设备不可用时自动回退 CPU。",
            "优化批量分析 UI 写回：单张完成时定点更新当前 Treeview 行，避免每张结果都重建整张缩略图列表，最终完成后再做一次稳定刷新。",
            "批量结束时输出最慢图片、最慢阶段、总耗时与平均耗时，便于定位是图片读取、判断、相似检测、候选评分、保存或元数据写回造成瓶颈。",
            "本轮仅做维护型小修，没有改变相似图算法、分析判断阈值、修复风格或安全清理规则。",
        ],
    },
    {
        "version": "1.1.4",
        "date": "2026-05-05",
        "items": [
            "相似图片检测继续增强：新增多尺度中心裁切、旋转鲁棒哈希、场景/主体摘要和低置信候选分级，可识别同人物同场景但横竖、裁切和人物大小变化明显的图片组；相似组列表窗口修复滚动区域与底部按钮布局。",
            "新增分析后相似图片自动检测与复核删除流程：基于缩略图感知哈希、颜色/亮度摘要、低分辨率结构向量、尺寸与可靠拍摄时间生成批次级相似组，不改写单张图片的识别问题、场景类型、人像信息、修复建议或不适合保留判断。",
            "分析器已从单文件扩展为 `analysis/` 包，按核心编排、曝光、高光、色彩、人像与清理候选拆分，`analyzer.py` 继续保留兼容入口。",
            "人像检测升级为候选与有效人脸双层结构，可区分真实正面人脸、背身/侧背身、画作/海报中的人脸与纹理误检；低置信度候选不再进入人像修复策略、多人脸评分或真人虚焦建议删除。",
            "新增更完整的场景、人像、曝光、高光恢复和色彩分析结果，支持窗景、剪影、低调氛围、建筑白墙/天空、自然高饱和等场景感知判断。",
            "“不适合保留”机制升级为通用复核管理：本轮已接入真实正面人像严重虚焦、严重全图糊片与极端不可恢复曝光问题；支持主界面复核框、批次复核对话框、二次确认与安全移入回收站/隔离目录。",
            "自动修复改为单图单策略、单图单力度：每张图先基于分析结果生成独立修复方案，再做候选评分、回退与是否保存决策；同一批图片不再共享固定算法链和统一强度。",
            "目录扫描新增“忽略目录前缀”设置，默认至少包含 `_repair`；任何以 `_repair` 开头的目录都会在根目录和任意子目录层级被整体跳过，避免把 `_repair`、`_repair_old`、`_repaired` 等输出目录重新扫回列表。",
            "目录扫描新增四种范围选择：扫描全部并包含子目录、只扫描当前目录、只扫描所有子目录、取消扫描；扫描摘要会同步输出扫描模式、跳过目录数量和导入图片数量，拖拽文件夹入口也统一遵守这套规则。",
            "修复准备窗口新增“强制修复不值得保留的图片”，默认关闭；开启后仅允许不适合保留图片进入统一修复链，修复后仍会执行单图评分、安全检查和可保留性回退，不会因为“强制”而无条件保存。",
            "去噪不再依赖孤立按钮，而是接入分析、规划、执行和回退全链路：分析阶段会给出 `noise_score`、`noise_level`、`denoise_profile` 与 `denoise_recommended`，修复阶段按人像、夜景暗部、纯净天空、建筑纹理等场景采用不同保护策略。",
            "主界面已移除独立“单图模式”入口和相关窗口代码；单张图片仍然通过主列表正常导入、分析和修复。",
            "批量分析与批量修复接入受控线程池，分析、修复与日志刷新都避免阻塞 Tk 主线程；输出路径生成增加锁保护，降低并发写入冲突风险。",
            "高反差窗景、剪影和低调氛围场景默认不再按普通欠曝强行提亮；不可恢复天空/白墙高光改为保亮度优先，避免统一压灰。",
            "色彩修复从更激进的全局饱和度思路改为更保守的 scene-aware vibrance，并增加对天空、肤色、木色、灰墙、白墙和自然高饱和场景的保护与回退。",
            "缩略图主列表与不适合保留复核列表均支持多选；批量修复完成提示改为可滚动自定义对话框，完整显示跳过、未保存、回退与失败原因。",
            "1.1.4 继续完善体验与配置层：顶部“设置”菜单收敛为统一“应用设置”面板，集中管理扫描忽略目录前缀、默认扫描模式与修复完成详情默认筛选，并为 app_settings.json 增加默认创建、损坏备份与回退默认值机制。",
            "扫描摘要新增按前缀聚合统计与可展开跳过目录明细：会记录每个被跳过目录的路径、命中前缀、跳过原因和层级位置，并可在“最近扫描摘要”对话框中滚动查看。",
            "修复完成详情窗口升级为可筛选列表视图，支持按已修复、已跳过、失败、强制尝试但未保存、强制尝试后保存、不适合保留相关、回退或未保存等维度快速筛选，并可复制当前筛选结果。",
            "分析进度窗口新增“取消分析”，关闭叉号走同一套取消清理；取消会清空本轮目标的分析结果、失败状态、推荐修复和不适合保留候选，保留文件列表并阻止已取消后台任务继续写回。",
            "分析与修复进度窗口新增耗时显示和用户可理解的阶段文案；目录扫描四选项窗口改为受屏幕高度限制的可滚动布局，底部“取消扫描”在小屏或缩放环境下仍可访问。",
        ],
    },
    {
        "version": "1.1.3",
        "date": "2026-05-05",
        "items": [
            "新增 portrait-aware 区域分析，为 AnalysisResult 增加 face/subject/background/highlight 区域、场景类型、曝光状态和修复策略字段。",
            "修复闪光灯人像与暗背景毕业照被误判为欠曝的问题，主体曝光正常时不再默认强行全局提亮。",
            "新增高调背景与亮背景人像识别，高亮白墙或浅色建筑场景不再默认走强全局压高光。",
            "增加局部人像增强、主体中间调增强、深色服装细节增强和高调背景保护等轻量局部修复方法。",
            "新增人像候选修复的评分与回退机制，并补上所有跳过场景的显式跳过理由与结果提示展示。",
            "进一步收紧人像分析：新增人脸候选明细和拒绝原因，降低椅背文字、绿植纹理、手部、衣物边缘误识别进入人像修复策略的概率。",
            "新增 `portrait_out_of_focus` 问题标签，以 validated face / subject 为核心判断人像主体虚焦；当背景或周边结构明显比脸更清楚时，可直接标记为高风险清理候选。",
            "新增通用 `cleanup_candidates` 结构，用于承载“不适合保留 / 建议删除”原因，而不再把清理逻辑写死在人像虚焦里。",
            "UI 新增独立的“不适合保留候选”框体，默认不勾选，支持单个勾选、批量切换、全选、取消全选，并要求二次确认后才执行安全清理。",
            "清理动作改为优先移入系统回收站；若系统不支持，则退回到项目内 `_cleanup_candidates` 隔离目录，避免永久删除。",
            "修复少量分析结果文案显示为乱码的问题，并增加问题文案兜底回退机制，确保异常文本不会直接展示给用户。",
            "修复输出方向归一问题：当原图依赖 EXIF 方向标签显示时，保存后的 JPEG / WebP 现在会把 Orientation 归一为 1，避免查看器再次旋转。",
        ],
    },
    {
        "version": "1.1.2",
        "date": "2026-05-02",
        "items": [
            "调整饱和度相关分析算法，降低自然绿植、花丛和阴影高纯度颜色场景的误判概率。",
            "将“饱和度偏高”的修复策略改为优先压制中高亮区域的极端颜色，减少整图发灰现象。",
            "修复竖图在连续修复后发生 90 度旋转的问题，输出 EXIF 方向统一归一。",
            "在 docs 下新增 technical 与 updates 子目录，用于分别存放技术文档和按版本号归档的更新文档。",
            "整理版本记录，补齐饱和度算法、文档体系和调试模式相关更新说明。",
        ],
    },
    {
        "version": "1.1.1",
        "date": "2026-04-30",
        "items": [
            "恢复快速启动入口，移除日常启动时的依赖检查，双击启动不再额外执行 pip 安装。",
            "修复图片导入与目录扫描主流程，确保单图、多图和文件夹入口能正常入列并完成扫描。",
            "修复全局拖拽导入，支持把资源管理器中的单张或多张图片拖入缩略图结果列表或主窗口区域。",
            "右侧预览区改为 HUD 加指标条图布局，移除图片预览，并让条图在较窄区域自动缩小字号以尽量显示更多指标。",
            "优化条图区域高度与二级弹窗尺寸，确保修复方案窗口底部“开始修复”按钮完整可见。",
            "分析任务进度改为按单张图片细分阶段累计推进，保留连续进度和多节点更新。",
            "修复完成后自动取消已处理图片的勾选，减少重复修复。",
            "新增调试模式：修复完成后可按本轮成功结果选择打开原图和修复图进行快速对比。",
            "更新历史已补齐至 1.1.1，并保留旧版本记录。",
        ],
    },
    {
        "version": "1.1.0",
        "date": "2026-04-30",
        "items": [
            "主界面重构为稳定的左右分栏和右侧四区布局，避免顶部进度区被遮挡。",
            "新增原生 Windows 拖入支持，可同时拖入多张图片或整个目录。",
            "新增只读 Console 面板，用于显示扫描、分析、修复和清理过程日志。",
            "修复对话框支持关闭后缀和覆盖原文件，默认仍为安全输出到新目录。",
            "修复输出保留 EXIF、DPI、ICC Profile 和可用的 XMP 元数据，并写入修改来源信息。",
            "移除默认可见水印接入，保留独立签名叠加模块但默认不启用。",
            "增强高饱和 HDR 场景和人像低饱和场景的误判抑制，降低运动图与人像样片的误报概率。",
            "完善模块文档、维护说明和数字签名能力边界说明。",
        ],
    },
    {
        "version": "1.0.0",
        "date": "2026-04-30",
        "items": [
            "列表管理改进：新导入图片默认标记为已选，分析选中优先处理所有已选项。",
            "修复输出保留原始 EXIF 与 DPI，并写入软件、作者和修改标记。",
            "新增累计统计、报表导出和问题检出率变化曲线。",
        ],
    },
    {
        "version": "0.9.0",
        "date": "2026-04-30",
        "items": [
            "列表支持右键移出当前图片，新增内容改为追加到现有列表。",
            "处理状态改为标签式显示，支持单击处理状态列切换。",
            "分析进度增加单张图片细分阶段提示。",
            "补充色彩寡淡与饱和度偏高的修复方法。",
            "新增模块维护文档。",
        ],
    },
    {
        "version": "0.8.0",
        "date": "2026-04-30",
        "items": [
            "进度模块独立为统一控制器，目录读取、分析和修复共用同一套状态更新逻辑。",
            "恢复导入、分析、修复三类任务的连续进度显示，并补回独立进度弹窗。",
            "分析维度新增色彩寡淡与饱和度偏高。",
        ],
    },
]

